import fs from 'node:fs/promises';
import crypto from 'node:crypto';
import {causalScore,marketConfirmation,stateFrom,hysteresisState,alphaClick} from './score.v2.mjs';
import {mergeEvidenceMemory} from './evidence-memory.mjs';

const mechCfg=JSON.parse(await fs.readFile('config/mechanisms.json','utf8'));
const policy=JSON.parse(await fs.readFile('config/policy.v2.json','utf8'));
const extraction=JSON.parse(await fs.readFile('data/extraction/latest.json','utf8').catch(()=>'{"mechanisms":{},"errors":[]}'));
const verification=JSON.parse(await fs.readFile('data/verification/latest.json','utf8').catch(()=>'{"mechanisms":{},"errors":[]}'));
const market=JSON.parse(await fs.readFile('data/market.json','utf8').catch(()=>'{"metrics":{},"context":{},"errors":[]}'));
const previous=JSON.parse(await fs.readFile('data/current.json','utf8').catch(()=>'{"mechanisms":{}}'));
const correlations=JSON.parse(await fs.readFile('data/correlation-memory.json','utf8').catch(()=>'{"mechanisms":{},"edges":[]}'));
const series=JSON.parse(await fs.readFile('data/series.json','utf8').catch(()=>'{"points":[]}'));
const ledger=JSON.parse(await fs.readFile('data/alpha-clicks.json','utf8').catch(()=>'{"signals":[]}'));
const retrieval=JSON.parse(await fs.readFile('data/retrieval/latest.json','utf8').catch(()=>'{"errors":[]}'));
const upstream=JSON.parse(await fs.readFile('data/upstream/latest.json','utf8').catch(()=>'{"errors":[]}'));
const now=new Date(),nowIso=now.toISOString(),runId=extraction.run_id||market.run_id||`run_${nowIso.replace(/[:.]/g,'-')}`;
const hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex').slice(0,22),tierStale={A:10,B:20,C:32};

function reliability(id){const x=correlations.mechanisms?.[id]||{};return {samples:x.alpha_5d?.samples||0,hit_rate:x.alpha_5d?.hit_rate??null,avg_return:x.alpha_5d?.avg_return??null,lead_to_confirm:x.lead_to_confirm?.rate??null}}
function invalidateFrom(v){return v?.verdict==='CONTRADICTED'&&(v.verified||[]).some(x=>x.contradiction)}
function scoreSafeEvidence(rows){return (rows||[]).map(e=>e?.engine==='openrouter_web_fallback'&&!e?.published_at?{...e,retrieved_at:null}:e)}
function adjustedCausal(evidence,verified,verdict){const c=causalScore(scoreSafeEvidence(evidence),verified,policy.event_clustering||{});if(verdict==='CONTRADICTED')c.score=Math.max(0,c.score-22);else if(verdict==='MIXED')c.score=Math.max(0,c.score-8);return c}
function memoryAwareCausal(observed,previousEvidence,verified,verdict){
  const evidence=mergeEvidenceMemory(observed,previousEvidence,policy,nowIso),observedPrepared=mergeEvidenceMemory(observed,[],policy,nowIso),observedCausal=adjustedCausal(observedPrepared,verified,verdict),combined=adjustedCausal(evidence,verified,verdict),carried=evidence.filter(e=>e.memory_status==='CARRIED');
  const avgWeight=carried.length?carried.reduce((a,e)=>a+Number(e.memory_weight||0),0)/carried.length:0,rawCombined=combined.score;
  if(carried.length&&rawCombined>observedCausal.score)combined.score=Math.round(Math.max(observedCausal.score,observedCausal.score+(rawCombined-observedCausal.score)*avgWeight));
  combined.memory={observed_items:observedPrepared.length,carried_items:carried.length,avg_carry_weight:+avgWeight.toFixed(3),observed_score:observedCausal.score,raw_combined_score:rawCombined,decayed_score:combined.score};
  return {evidence,observedPrepared,observedCausal,causal:combined};
}
function benchmarkFor(id){if(/DIESEL|TANKER|CRUDE|ATLANTIC|CEYHAN|LNG|OIL_SERVICE/.test(id))return 'XLE';if(/ARSENAL|ROCKET|ENERGETICS|DRONE|COUNTER_UAS|UNDERWATER|MILITARY|EUROPE_STRATEGIC/.test(id))return 'ITA';if(/AI_|ROBOTICS|CYBER/.test(id))return 'QQQ';if(/JAPAN/.test(id))return 'EWJ';if(/NUCLEAR/.test(id))return 'URA';if(/RARE_EARTH|ALUMINIUM/.test(id))return 'XME';if(/REFINANCING/.test(id))return 'IWM';return policy.market?.benchmark_default||'^GSPC'}
function marketVote(m){const bt=benchmarkFor(m.id),benchmark=market.context?.[bt]||market.context?.['^GSPC']||null;return marketConfirmation({positive:(m.positive||[]).map(t=>market.metrics?.[t]).filter(Boolean),negative:(m.negative||[]).map(t=>market.metrics?.[t]).filter(Boolean),benchmark})}
function eventizeCluster(m,c){const rep=c.rep||{},observed=c.members?.map(x=>Date.parse(x.published_at||'')).filter(Number.isFinite).sort((a,b)=>a-b)[0];return {id:hash(`${m.id}|${c.phase}|${c.signal}|${c.claim}`),mechanism_id:m.id,run_id:runId,phase:c.phase,signal:c.signal,claim:c.claim,observed_at:Number.isFinite(observed)?new Date(observed).toISOString():(rep.published_at||null),ingested_at:nowIso,source_count:c.member_count||1,domains:c.domains||[],source_urls:c.source_urls||[],official:Boolean((c.members||[]).some(x=>x.official)),representative_source:rep.source_name||rep.source_domain||null,representative_url:rep.source_url||null,source_grade:rep.source_grade??null}}
function basketPrices(tickers){const x={};for(const t of tickers||[]){const p=market.metrics?.[t]?.price;if(Number.isFinite(p))x[t]=p}return x}
function avgReturn(entries,current){const vals=[];for(const [t,p0] of Object.entries(entries||{})){const p1=current?.[t]?.price;if(Number.isFinite(p0)&&Number.isFinite(p1)&&p0!==0)vals.push((p1/p0-1)*100)}return vals.length?vals.reduce((a,b)=>a+b,0)/vals.length:null}

const mechanisms={},transitions=[];
for(const m of mechCfg.mechanisms){
  const x=extraction.mechanisms?.[m.id],v=verification.mechanisms?.[m.id],prev=previous.mechanisms?.[m.id];
  if(!x){if(prev){const age=(Date.now()-Date.parse(prev.last_run||previous.updated_at||0))/36e5,stale=age>(tierStale[m.tier]||24),mkt=marketVote(m);mechanisms[m.id]={...prev,market:mkt,state:stale?'STALE':prev.state,raw_state:stale?'STALE':prev.raw_state||prev.state,stale,updated_market_at:market.generated_at||null}}continue}
  const observedEvidence=x.evidence||[],verified=v?.verified||[],mem=memoryAwareCausal(observedEvidence,prev?.evidence||[],verified,v?.verdict),evidence=mem.evidence,causal=mem.causal,mkt=marketVote(m),invalidated=invalidateFrom(v),rawState=stateFrom({causal,market:mkt,invalidated,policy}),gate=hysteresisState({raw:rawState,previous:prev?.state||null,pending:prev?.hysteresis?.pending||null,causal,invalidated,policy}),state=gate.state,rel=reliability(m.id),alpha=alphaClick({causal,market:mkt,policy,reliability:rel,invalidated,state}),events=(mem.observedCausal.event_clusters||[]).map(c=>eventizeCluster(m,c));
  const obj={id:m.id,label:m.label,tier:m.tier,state,raw_state:rawState,score:causal.score,previous_state:prev?.state||null,score_delta:causal.score-(prev?.score||0),summary:x.summary,material_change:Math.abs(causal.score-(prev?.score||0))>=8||state!==prev?.state,observed_evidence:mem.observedPrepared,evidence,verified,verifier:{verdict:v?.verdict||'NOT_RUN',summary:v?.summary||'',next_check:v?.next_check||''},events,event_stats:{observed_unique:mem.observedCausal.event_count||0,observed_duplicates:mem.observedCausal.duplicate_count||0,memory_unique:causal.event_count||0,memory_duplicates:causal.duplicate_count||0},memory:causal.memory,expected_next:x.expected_next||[],invalidation:x.invalidation||[],market:mkt,alpha,reliability:rel,hysteresis:{raw_state:rawState,pending:gate.pending,reason:gate.reason,applied:gate.applied},sensors:{lead:causal.counts.LEAD,confirm:causal.counts.CONFIRM,lag:causal.counts.LAG,lag_share:+causal.lag_share.toFixed(3),domains:causal.domains,events:causal.event_count||0,duplicates_removed:causal.duplicate_count||0},positive:m.positive||[],negative:m.negative||[],last_run:nowIso,model:x.model,usage:x.usage||null,candidate_count:x.candidate_count||0,official_candidate_count:x.official_candidate_count||0,query_trace:(x.query_trace||[]).map(q=>({query_id:q.query_id,phase:q.phase,signal:q.signal,q:q.q,engines:q.engines}))};
  mechanisms[m.id]=obj;if(!prev||prev.state!==state||Math.abs(obj.score_delta)>=10)transitions.push({mechanism_id:m.id,from:prev?.state||null,to:state,raw_to:rawState,score:obj.score,delta:obj.score_delta,hysteresis:obj.hysteresis,memory:obj.memory,at:nowIso});
}

const prevAlpha=previous.mechanisms||{};
for(const m of mechCfg.mechanisms){const cur=mechanisms[m.id];if(!cur)continue;const was=prevAlpha[m.id]?.alpha?.eligible===true;if(cur.alpha?.eligible&&!was){const entry=basketPrices(cur.positive),benchTicker=cur.market?.benchmark||benchmarkFor(m.id),bench=market.context?.[benchTicker]?.price;if(Object.keys(entry).length)ledger.signals.push({id:`alpha_${hash(`${m.id}|${nowIso}`)}`,mechanism_id:m.id,label:m.label,created_at:nowIso,run_id:runId,alpha_score:cur.alpha.score,causal_score:cur.score,market_score:cur.market.score,crowding:cur.market.crowding,state:cur.state,tickers:cur.positive,entry_prices:entry,benchmark_ticker:benchTicker,benchmark_entry:Number.isFinite(bench)?bench:null,horizons:{d1:null,d5:null,d20:null},status:'OPEN'})}}
for(const s of ledger.signals){const ageDays=(Date.now()-Date.parse(s.created_at))/864e5,mechanism=mechanisms[s.mechanism_id];for(const [key,days] of [['d1',1],['d5',5],['d20',20]]){if(s.horizons?.[key]||ageDays<days)continue;const r=avgReturn(s.entry_prices,market.metrics),b0=s.benchmark_entry,b1=market.context?.[s.benchmark_ticker||'^GSPC']?.price,br=Number.isFinite(b0)&&Number.isFinite(b1)&&b0?((b1/b0)-1)*100:null;if(r!=null)s.horizons[key]={resolved_at:nowIso,basket_return:+r.toFixed(2),benchmark_return:br==null?null:+br.toFixed(2),relative_return:br==null?null:+(r-br).toFixed(2),hit:r>0,relative_hit:br==null?null:r>br}}if(mechanism?.state==='SATURATED')s.status='SATURATED';else if(mechanism?.state==='INVALIDATED')s.status='INVALIDATED';else if(s.horizons?.d20)s.status='RESOLVED'}

series.points.push({run_id:runId,ts:nowIso,mechanisms:Object.fromEntries(Object.entries(mechanisms).map(([id,x])=>[id,{score:x.score,state:x.state,raw_state:x.raw_state,market_score:x.market?.score||0,crowding:x.market?.crowding||0,rel5:x.market?.avg?.rel5||0,rel2h:x.market?.avg?.rel2h||0,lead:x.sensors?.lead||0,confirm:x.sensors?.confirm||0,lag:x.sensors?.lag||0,events:x.sensors?.events||0,memory_carried:x.memory?.carried_items||0,alpha:x.alpha?.eligible||false}]))});if(series.points.length>1600)series.points=series.points.slice(-1600);
const current={version:'2.5.0',updated_at:nowIso,run_id:runId,health:{retrieval_errors:(retrieval.errors||[]).length,upstream_errors:(upstream.errors||[]).length,extraction_errors:(extraction.errors||[]).length,verification_errors:(verification.errors||[]).length,market_errors:(market.errors||[]).length,mechanisms:Object.keys(mechanisms).length},transitions,mechanisms};
const run={version:'2.5.0',run_id:runId,updated_at:nowIso,transitions,mechanisms:Object.values(mechanisms).filter(x=>x.material_change),health:current.health};
await fs.mkdir('data/history-v2',{recursive:true});await fs.writeFile('data/current.json',JSON.stringify(current,null,2)+'\n');await fs.writeFile('data/series.json',JSON.stringify(series,null,2)+'\n');await fs.writeFile('data/alpha-clicks.json',JSON.stringify(ledger,null,2)+'\n');await fs.writeFile(`data/history-v2/${runId}.json`,JSON.stringify(run,null,2)+'\n');
console.log(`assemble ${runId}: ${Object.keys(mechanisms).length} mechanisms, ${transitions.length} transitions, ${ledger.signals.length} alpha signals total, evidence-memory=v2.5`);
