import fs from 'node:fs/promises';

const read=async(path,fallback={})=>JSON.parse(await fs.readFile(path,'utf8').catch(()=>JSON.stringify(fallback)));
const [cfg,seeds,poolPolicy,q1,qx,retr,current,broker,inv,execPolicy,causalPolicy,plan,paper,journal,modelHealth]=await Promise.all([
  read('config/mechanisms.json',{mechanisms:[]}),read('config/investment-seeds.json',{mechanisms:{}}),read('config/company-pool-policy.json',{mechanisms:{},defaults:{}}),read('config/queries.v2.json',{mechanisms:{}}),read('config/queries.v2.extra.json',{mechanisms:{}}),read('data/retrieval/latest.json',{mechanisms:{},coverage:{}}),read('data/current.json',{mechanisms:{},health:{}}),read('data/broker.json',{instruments:{},stats:{}}),read('data/investment-layer.json',{strategies:{},summary:{}}),read('config/execution-policy.json',{}),read('config/policy.v2.json',{}),read('data/execution-plan.json',{regime:{},summary:{}}),read('data/paper-portfolio.json',{positions:[],stats:{}}),read('data/trade-journal.json',{trades:[],stats:{}}),read('data/model-health.json',{models:{}})
]);
const queries={...(q1.mechanisms||{}),...(qx.mechanisms||{})},uniq=a=>[...new Set(a.filter(Boolean))];
const poolFor=id=>({...poolPolicy.defaults,...(poolPolicy.mechanisms?.[id]||{})});
const phases=q=>['lead','confirm','lag'].flatMap(p=>(q?.[p]||[]).map(x=>({...x,phase:p.toUpperCase()})));
const engineRows=qRows=>qRows.flatMap(q=>Object.entries(q.engines||{}).map(([engine,x])=>({query_id:q.query_id,engine,...x})));
const countHits=e=>Number.isFinite(Number(e?.count))?Number(e.count):0;
const queryHasNativeHit=q=>Object.values(q.engines||{}).some(e=>e?.ok===true&&countHits(e)>0);
const querySucceededEmpty=q=>{const es=Object.values(q.engines||{});return es.some(e=>e?.ok===true)&&!queryHasNativeHit(q)};
const issue=(code,severity,detail)=>({code,severity,detail});
const rows=[];
for(const m of cfg.mechanisms||[]){
  const pp=poolFor(m.id),seedRows=seeds.mechanisms?.[m.id]||[],directSeeds=seedRows.filter(x=>x[2]==='DIRECT'),qCfg=queries[m.id]||{},configuredQueries=phases(qCfg),r=retr.mechanisms?.[m.id]||{},qRows=r.queries||[],scheduledIds=new Set(r.scheduled_query_ids||qRows.filter(x=>!x.backstop).map(x=>x.query_id)),reportedIds=new Set(qRows.map(x=>x.query_id)),missingScheduled=[...scheduledIds].filter(x=>!reportedIds.has(x)),scheduledRows=qRows.filter(x=>scheduledIds.has(x.query_id)),engines=engineRows(qRows),nativeHits=engines.reduce((a,e)=>a+countHits(e),0),failedEngines=engines.filter(e=>e.ok===false&&!e.skipped),timeouts=failedEngines.filter(e=>/timeout|aborted/i.test(String(e.error||''))),zeroQueries=scheduledRows.filter(querySucceededEmpty),candidates=r.candidates||[],fallbackCandidates=candidates.filter(x=>x.fallback||x.engine==='openrouter_web_fallback'),officialCandidates=candidates.filter(x=>x.official===true||x.engine==='official_rss'),cur=current.mechanisms?.[m.id]||{},observed=cur.observed_evidence||[],evidence=cur.evidence||[],validEvidence=evidence.filter(x=>x.valid!==false),domains=uniq(validEvidence.map(x=>x.source_domain)),strategy=inv.strategies?.[m.id]||{},ranked=strategy.ranked_candidates||strategy.top5||[],top5=strategy.top5||ranked.slice(0,5),directTop=top5.filter(x=>x.exposure==='DIRECT'),brokerVerifiedTop=top5.filter(x=>x.broker_verified===true),noMarketTop=top5.filter(x=>x.market?.quality==='NO_MARKET'||!Number.isFinite(Number(x.market?.price))),problems=[];
  if(seedRows.length<Number(pp.min_pool||5)) problems.push(issue('SEED_POOL_TOO_SMALL','HIGH',`${seedRows.length} candidates; mechanism minimum ${pp.min_pool}.`));
  else if(seedRows.length<Number(pp.target_pool||pp.min_pool||5)) problems.push(issue('SEED_POOL_BELOW_TARGET','LOW',`${seedRows.length}/${pp.target_pool} target; intentionally acceptable above minimum ${pp.min_pool}.`));
  if(directSeeds.length<Number(pp.min_direct||0)) problems.push(issue('DIRECT_EXPOSURE_THIN','HIGH',`${directSeeds.length} DIRECT candidates; mechanism minimum ${pp.min_direct}.`));
  if(configuredQueries.length===0) problems.push(issue('NO_QUERY_CONFIG','CRITICAL','No retrieval queries configured.'));
  if(missingScheduled.length) problems.push(issue('SCHEDULED_QUERY_MISSING','HIGH',`${missingScheduled.length} scheduled queries were not reported: ${missingScheduled.join(', ')}`));
  const nativeRatio=scheduledRows.length?zeroQueries.length/scheduledRows.length:0;
  if(scheduledRows.length&&nativeRatio>=.75&&candidates.length<2) problems.push(issue('NATIVE_SEARCH_BLIND','MEDIUM',`${zeroQueries.length}/${scheduledRows.length} scheduled queries returned no native hits and evidence remains thin.`));
  else if(scheduledRows.length&&nativeRatio>=.75) problems.push(issue('NATIVE_SEARCH_ZERO_BUT_RESCUED','LOW',`${zeroQueries.length}/${scheduledRows.length} scheduled queries were natively empty, but backstop/official/rescue produced ${candidates.length} candidates.`));
  if(failedEngines.length&&candidates.length<2) problems.push(issue('RETRIEVER_ERRORS_UNRESCUED','MEDIUM',`${failedEngines.length} source failures (${timeouts.length} timeout/abort) with thin evidence.`));
  else if(failedEngines.length) problems.push(issue('SOURCE_DEGRADED_BUT_RESILIENT','LOW',`${failedEngines.length} source failures were absorbed by other retrieval layers.`));
  if(candidates.length===0){const hot=['WATCH','ARMING','ACTIVE','SATURATED'].includes(cur.state)||m.tier==='A';problems.push(issue('NO_RETRIEVAL_CANDIDATES',hot?'HIGH':'MEDIUM','No candidate evidence retrieved in the latest run.'))}
  else if(nativeHits===0&&fallbackCandidates.length) problems.push(issue('FALLBACK_USED','LOW',`${fallbackCandidates.length} web-rescue candidates supplemented native search.`));
  if(observed.length===0&&candidates.length>0) problems.push(issue('NO_OBSERVED_EVIDENCE','LOW','Candidates exist but none survived extraction/event gates this cycle.'));
  if(ranked.length<Number(pp.min_pool||5)) problems.push(issue('RANKED_POOL_SHORT','HIGH',`Investment layer has ${ranked.length}/${pp.min_pool} required ranked candidates.`));
  if(top5.length<Math.min(5,Number(pp.min_pool||5))) problems.push(issue('TOP5_SHORT','HIGH',`Executable recommendation set has ${top5.length}/5 candidates.`));
  if(Number(pp.min_direct||0)>=3&&directTop.length<Math.min(3,Number(pp.min_direct))) problems.push(issue('TOP5_DIRECT_THIN','MEDIUM',`${directTop.length}/5 Top candidates are DIRECT exposure.`));
  if(noMarketTop.length) problems.push(issue('MARKET_DATA_GAPS','HIGH',`${noMarketTop.length} Top candidates lack usable market price telemetry.`));
  if(broker.authoritative===true&&brokerVerifiedTop.length<top5.length) problems.push(issue('T212_LIVE_GAPS','HIGH',`${brokerVerifiedTop.length}/${top5.length} Top candidates live-verified on T212.`));
  const severityRank={CRITICAL:4,HIGH:3,MEDIUM:2,LOW:1},worst=Math.max(0,...problems.map(x=>severityRank[x.severity]||0)),grade=worst>=4?'F':worst===3?'C':worst===2?'B':worst===1?'A-':'A';
  rows.push({id:m.id,label:m.label,tier:m.tier,grade,companies:{seed_count:seedRows.length,target:Number(pp.target_pool||5),minimum:Number(pp.min_pool||5),direct_minimum:Number(pp.min_direct||0),display_limit:Number(pp.display_limit||5),direct_seed_count:directSeeds.length,proxy_seed_count:seedRows.length-directSeeds.length,ranked_count:ranked.length,top5_count:top5.length,top5_direct:directTop.length,ranked_symbols:ranked.map(x=>x.symbol),top5_symbols:top5.map(x=>x.symbol)},search:{configured_queries:configuredQueries.length,scheduled_queries:Number(r.scheduled_query_count??scheduledIds.size),reported_queries:qRows.length,missing_scheduled_queries:missingScheduled.length,scheduled_phases:r.scheduled_phases||[],backstop:r.backstop||null,native_hits:nativeHits,zero_native_queries:zeroQueries.length,zero_native_ratio:scheduledRows.length?+nativeRatio.toFixed(3):null,engine_failures:failedEngines.length,timeouts:timeouts.length,retrieval_candidates:candidates.length,fallback_candidates:fallbackCandidates.length,official_candidates:officialCandidates.length},evidence:{observed:observed.length,total:evidence.length,valid:validEvidence.length,unique_domains:domains.length,state:cur.state||'UNKNOWN',causal_score:Number(cur.score||0)},investment:{action:strategy.action||null,opportunity_score:Number(strategy.opportunity_score||0),transmission_score:Number(strategy.transmission_score||0),quality:strategy.quality||null,broker_gate:Boolean(strategy.broker_strict),broker_verified_top5:brokerVerifiedTop.length},issues:problems});
}
const severityCounts={critical:0,high:0,medium:0,low:0};for(const r of rows)for(const x of r.issues){const k=x.severity.toLowerCase();severityCounts[k]=(severityCounts[k]||0)+1}
const seedSymbols=uniq(Object.values(seeds.mechanisms||{}).flat().map(x=>x[0])),protectedSet=new Set((execPolicy.protected_symbols||[]).map(x=>String(x).toUpperCase())),positions=paper.positions||[],sgmoqIsolated=protectedSet.has('SGMOQ')&&!positions.some(x=>String(x.symbol||'').toUpperCase().startsWith('SGMOQ')),budgetOk=Number(execPolicy.capital?.initial_budget_usd)===500&&Number(execPolicy.capital?.max_order_usd)===80&&Number(execPolicy.capital?.max_open_positions)===6,liveOff=execPolicy.mode==='SHADOW_ONLY'&&execPolicy.execution?.auto_live_orders===false&&plan.summary?.live_execution===false,globalIssues=[];
if(!sgmoqIsolated)globalIssues.push(issue('SGMOQ_ISOLATION_BROKEN','CRITICAL','SGMOQ guardrail or paper-sleeve isolation failed.'));
if(!budgetOk)globalIssues.push(issue('CAPITAL_INVARIANTS_CHANGED','CRITICAL','Expected $500 budget / $80 max order / 6 slots.'));
if(!liveOff)globalIssues.push(issue('LIVE_EXECUTION_NOT_OFF','CRITICAL','Autonomous live execution must remain disabled.'));
if(!broker.availability_gate)globalIssues.push(issue('T212_SHADOW_GATE_BLOCKED','HIGH',`Broker mode ${broker.mode||'UNKNOWN'} does not permit even curated shadow eligibility.`));
else if(broker.authoritative!==true)globalIssues.push(issue('T212_CURATED_NOT_LIVE','LOW','Shadow uses the curated T212 universe; official live catalogue matching is optional and not a shadow blocker.'));
const session=plan.regime?.session||{},fresh=plan.regime?.freshness?.fresh;
if(session.regular_open===true&&fresh===false)globalIssues.push(issue('MARKET_TELEMETRY_STALE','HIGH','Regular session is open but benchmark freshness gate failed.'));
else if(session.regular_open===false)globalIssues.push(issue('MARKET_CLOSED','LOW',`Regular US session is closed (${session.label||'CLOSED'}); new entries correctly remain blocked.`));
if((current.health?.retrieval_errors||0)>0)globalIssues.push(issue('CURRENT_RETRIEVAL_ERRORS','LOW',`${current.health.retrieval_errors} raw retrieval-source errors; resilience is judged mechanism by mechanism.`));
if((current.health?.verification_errors||0)>0)globalIssues.push(issue('CURRENT_VERIFICATION_ERRORS','LOW',`${current.health.verification_errors} verification errors in current health.`));
const duplicateSymbols=positions.map(x=>String(x.symbol||'').toUpperCase()).filter((x,i,a)=>a.indexOf(x)!==i);if(duplicateSymbols.length)globalIssues.push(issue('SHADOW_DUPLICATE_POSITION','CRITICAL',`Duplicate paper positions: ${uniq(duplicateSymbols).join(', ')}`));
if(positions.length>Number(execPolicy.capital?.max_open_positions||6))globalIssues.push(issue('SHADOW_SLOT_OVERFLOW','CRITICAL',`${positions.length} positions exceed slot cap.`));
if(Number(paper.cash_usd||0)<-0.01)globalIssues.push(issue('SHADOW_NEGATIVE_CASH','CRITICAL',`Cash is ${paper.cash_usd}.`));
const navCalc=Number(paper.cash_usd||0)+positions.reduce((a,x)=>a+Number(x.market_value_usd||0),0);if(Math.abs(navCalc-Number(paper.nav_usd||0))>.25)globalIssues.push(issue('SHADOW_NAV_MISMATCH','HIGH',`Ledger NAV ${paper.nav_usd} vs recomputed ${navCalc.toFixed(2)}.`));
const oversizeTrades=(journal.trades||[]).filter(x=>String(x.side||'').toUpperCase()==='BUY'&&Number(x.notional_usd||0)>Number(execPolicy.capital?.max_order_usd||80)+.01);if(oversizeTrades.length)globalIssues.push(issue('SHADOW_ORDER_CAP_BROKEN','CRITICAL',`${oversizeTrades.length} BUY journal entries exceed $80.`));
const activeModels=new Set([causalPolicy.model,...(causalPolicy.model_pool||[]),causalPolicy.verifier_model,causalPolicy.extractor?.fallback_model].filter(Boolean));
const badModels=Object.entries(modelHealth.models||{}).filter(([name,x])=>activeModels.has(name)&&Number(x.fail||0)>0&&Number(x.success||0)===0).map(([name,x])=>({name,fail:x.fail,last_error:x.last_error||null}));if(badModels.length)globalIssues.push(issue('ACTIVE_MODEL_UNHEALTHY','MEDIUM',`${badModels.length} currently configured model endpoints have failures and no successes.`));
const report={version:'3.1.0',generated_at:new Date().toISOString(),run_id:current.run_id||retr.run_id||plan.run_id||null,verdict:globalIssues.some(x=>x.severity==='CRITICAL')?'FAIL':(globalIssues.some(x=>x.severity==='HIGH')||rows.some(x=>x.grade==='C'||x.grade==='F'))?'NEEDS_ATTENTION':'HEALTHY',summary:{mechanisms:rows.length,mechanism_grades:Object.fromEntries(['A','A-','B','C','F'].map(g=>[g,rows.filter(x=>x.grade===g).length])),seed_rows:Object.values(seeds.mechanisms||{}).reduce((a,x)=>a+x.length,0),unique_seed_symbols:seedSymbols.length,mechanisms_below_min_pool:rows.filter(x=>x.companies.seed_count<x.companies.minimum).length,mechanisms_below_direct_min:rows.filter(x=>x.companies.direct_seed_count<x.companies.direct_minimum).length,mechanisms_fallback_used:rows.filter(x=>x.search.fallback_candidates>0).length,mechanisms_no_retrieval_candidates:rows.filter(x=>x.search.retrieval_candidates===0).length,severity_counts:severityCounts},trading212:{mode:broker.mode||'UNKNOWN',authoritative:Boolean(broker.authoritative),catalogue_verified:Boolean(broker.catalogue_verified),availability_gate:Boolean(broker.availability_gate),shadow_eligible:Boolean(broker.shadow_eligible),live_execution_eligible:Boolean(broker.live_execution_eligible),seed_symbols:Number(broker.stats?.seed_symbols||0),verified:Number(broker.stats?.verified||0),assumed_available:Number(broker.stats?.assumed_available||0),coverage:Number(broker.coverage||0),errors:broker.errors||[],notices:broker.notices||[]},shadow:{mode:paper.mode||execPolicy.mode,budget_usd:Number(execPolicy.capital?.initial_budget_usd||0),max_order_usd:Number(execPolicy.capital?.max_order_usd||0),max_positions:Number(execPolicy.capital?.max_open_positions||0),cash_usd:Number(paper.cash_usd||0),nav_usd:Number(paper.nav_usd||0),open_positions:positions.length,available_slots:Number(paper.stats?.available_slots??0),trades:(journal.trades||[]).length,sgmoq_isolated:sgmoqIsolated,live_execution_off:liveOff,market_entry_allowed:Boolean(plan.regime?.entry_allowed),market_block_reason:plan.regime?.block_reason||null,market_session:session,market_freshness:plan.regime?.freshness||null,nav_recomputed:+navCalc.toFixed(2)},model_health:{active_models:[...activeModels],active_unhealthy:badModels,historical_model_count:Object.keys(modelHealth.models||{}).length},global_issues:globalIssues,mechanisms:rows};
await fs.writeFile('data/audit-v3.json',JSON.stringify(report,null,2)+'\n');
console.log(`audit v3.1: verdict=${report.verdict} mechanisms=${rows.length} belowPool=${report.summary.mechanisms_below_min_pool} belowDirect=${report.summary.mechanisms_below_direct_min} noCandidates=${report.summary.mechanisms_no_retrieval_candidates} t212=${report.trading212.mode} shadow=${report.shadow.mode} market=${report.shadow.market_block_reason||'OPEN'}`);
