const STATE_RANK={UNKNOWN:-1,DORMANT:0,STALE:0,WATCH:1,ARMING:2,ACTIVE:3,INVALIDATED:-2,SATURATED:4};
const WAVE_RANK={DISCOVERY:0,PRE_WAVE:1,EARLY_WAVE:2,IN_SYNC:3,LATE_WAVE:4,SATURATED:5};
const round=(x,d=2)=>Number.isFinite(Number(x))?+Number(x).toFixed(d):null;
export function normalizeMechanisms(mechanisms){if(Array.isArray(mechanisms))return Object.fromEntries(mechanisms.filter(x=>x?.id).map(x=>[x.id,x]));return mechanisms&&typeof mechanisms==='object'?mechanisms:{}}
export function isStatePromotion(t){const from=STATE_RANK[t?.from]??-1,to=STATE_RANK[t?.to]??-1;return ['WATCH','ARMING','ACTIVE'].includes(t?.to)&&to>from}
export function isWavePromotion(t){const from=WAVE_RANK[t?.from]??-1,to=WAVE_RANK[t?.to]??-1;return ['PRE_WAVE','EARLY_WAVE'].includes(t?.to)&&to>from}
export function benchmarkFor(id){return /DIESEL|TANKER|CRUDE|ATLANTIC|CEYHAN|LNG|OIL_SERVICE/.test(id)?'XLE':/ARSENAL|ROCKET|ENERGETICS|DRONE|COUNTER_UAS|UNDERWATER|MILITARY|EUROPE_STRATEGIC/.test(id)?'ITA':/AI_|ROBOTICS|CYBER/.test(id)?'QQQ':/JAPAN/.test(id)?'EWJ':/NUCLEAR/.test(id)?'URA':/RARE_EARTH|ALUMINIUM/.test(id)?'XME':/REFINANCING/.test(id)?'IWM':'^GSPC'}
export function configuredBasket(id,seeds,size=5){return (seeds?.mechanisms?.[id]||[]).slice(0,size).map((x,i)=>({symbol:x[0],fit:Number(x[1])||0,exposure:x[2]||'UNKNOWN',rank:i+1}))}
export function collectSignals(snapshot,{seeds,policy,researchOnly=false,sourceFile=null}={}){
 const mechs=normalizeMechanisms(snapshot?.mechanisms),state=(snapshot?.transitions||[]).filter(isStatePromotion),wave=(snapshot?.wave_transitions||[]).filter(isWavePromotion),ids=[...new Set([...state.map(x=>x.mechanism_id),...wave.map(x=>x.mechanism_id)])],runId=snapshot?.run_id||`unknown_${snapshot?.updated_at||snapshot?.generated_at||'run'}`,at=snapshot?.updated_at||snapshot?.generated_at||new Date().toISOString(),size=Number(policy?.basket_size||5),out=[];
 for(const id of ids){const m=mechs[id]||{},st=state.filter(x=>x.mechanism_id===id),wv=wave.filter(x=>x.mechanism_id===id),first=st[0]||wv[0]||{},memory=st[0]?.memory||{},basket=configuredBasket(id,seeds,size),priced=Number.isFinite(Number(m?.crowd?.priced_in))?Number(m.crowd.priced_in):Number.isFinite(Number(wv[0]?.priced_in))?Number(wv[0].priced_in):null,causal=Number.isFinite(Number(m?.score))?Number(m.score):Number(first?.score||0);
   if(!basket.length)continue;
   const triggerParts=[...st.map(x=>`STATE:${x.from}->${x.to}`),...wv.map(x=>`WAVE:${x.from}->${x.to}`)];
   out.push({id:`${runId}:${id}:${triggerParts.join('+')}`,run_id:runId,mechanism_id:id,label:m.label||id,signal_at:at,research_only:Boolean(researchOnly),source_file:sourceFile,entry_rule:'NEXT_SESSION_OPEN',basket_source:'CONFIGURED_SEED_ORDER',basket,benchmark:benchmarkFor(id),global_benchmark:'^GSPC',triggers:triggerParts,state:m.state||st.at(-1)?.to||null,wave_phase:m?.crowd?.phase||wv.at(-1)?.to||null,causal_score:round(causal,1),score_delta:round(m?.score_delta??first?.delta??0,1),priced_in:round(priced,1),causal_gap:priced==null?null:round(causal-priced,1),observed_items:Number(memory.observed_items||0),carried_items:Number(memory.carried_items||0),observed_score:round(memory.observed_score,1),created_at:new Date().toISOString(),status:'PENDING_ENTRY',horizons:{}})
 }
 return out
}
function rowsFromMetric(metric){return (metric?.daily_bars||[]).map(x=>({t:Date.parse(x.t),open:Number(x.open),close:Number(x.close)})).filter(x=>Number.isFinite(x.t)&&Number.isFinite(x.close)).sort((a,b)=>a.t-b.t)}
export function evaluatePath(metric,signalAt,horizons=[1,3,5,10,20]){const rows=rowsFromMetric(metric),ts=Date.parse(signalAt);if(!Number.isFinite(ts)||!rows.length)return {entry:null,horizons:{}};const i=rows.findIndex(x=>x.t>ts&&Number.isFinite(x.open)&&x.open>0);if(i<0)return {entry:null,horizons:{}};const entry={index:i,t:new Date(rows[i].t).toISOString(),price:round(rows[i].open,6)},out={};for(const h of horizons){const j=i+Number(h)-1;if(j>=rows.length)continue;const exit=rows[j];out[h]={sessions:Number(h),exit_at:new Date(exit.t).toISOString(),exit_price:round(exit.close,6),return_pct:round((exit.close/rows[i].open-1)*100,4)}}return {entry,horizons:out}}
const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
const median=a=>{if(!a.length)return null;const b=[...a].sort((x,y)=>x-y),i=Math.floor(b.length/2);return b.length%2?b[i]:(b[i-1]+b[i])/2}
export function evaluateSignal(signal,market,horizons=[1,3,5,10,20],minCoverage=.6){const symbols=signal.basket||[],paths=Object.fromEntries(symbols.map(x=>[x.symbol,evaluatePath(market?.metrics?.[x.symbol],signal.signal_at,horizons)])),sector=evaluatePath(market?.context?.[signal.benchmark],signal.signal_at,horizons),global=evaluatePath(market?.context?.[signal.global_benchmark||'^GSPC'],signal.signal_at,horizons),out={};let entryCount=0;for(const p of Object.values(paths))if(p.entry)entryCount++;
 for(const h of horizons){const available=symbols.map(x=>({symbol:x.symbol,ret:paths[x.symbol]?.horizons?.[h]?.return_pct})).filter(x=>Number.isFinite(x.ret)),min=Math.max(1,Math.ceil(symbols.length*minCoverage));if(available.length<min)continue;const basketRet=mean(available.map(x=>x.ret)),s=sector.horizons?.[h]?.return_pct,g=global.horizons?.[h]?.return_pct;out[h]={sessions:Number(h),coverage:round(available.length/symbols.length*100,1),members:available.length,basket_return_pct:round(basketRet,4),sector_return_pct:Number.isFinite(s)?round(s,4):null,spx_return_pct:Number.isFinite(g)?round(g,4):null,alpha_sector_pct:Number.isFinite(s)?round(basketRet-s,4):null,alpha_spx_pct:Number.isFinite(g)?round(basketRet-g,4):null,by_symbol:Object.fromEntries(available.map(x=>[x.symbol,round(x.ret,4)]))}}
 const maxH=Math.max(...horizons),status=out[maxH]?'MATURED':entryCount>=Math.max(1,Math.ceil(symbols.length*minCoverage))?'ACTIVE':'PENDING_ENTRY';return {...signal,status,entry_coverage_pct:round(entryCount/Math.max(1,symbols.length)*100,1),entries:Object.fromEntries(Object.entries(paths).filter(([,p])=>p.entry).map(([s,p])=>[s,p.entry])),benchmark_entry:sector.entry,global_benchmark_entry:global.entry,horizons:out,updated_at:new Date().toISOString()}}
function statsFor(signals,h){const rows=signals.map(s=>s?.horizons?.[h]).filter(Boolean),abs=rows.map(x=>x.basket_return_pct).filter(Number.isFinite),aS=rows.map(x=>x.alpha_sector_pct).filter(Number.isFinite),aG=rows.map(x=>x.alpha_spx_pct).filter(Number.isFinite),samples=abs.length;return {samples,avg_return_pct:round(mean(abs),3),median_return_pct:round(median(abs),3),positive_rate_pct:samples?round(abs.filter(x=>x>0).length/samples*100,1):null,avg_alpha_sector_pct:round(mean(aS),3),alpha_sector_hit_rate_pct:aS.length?round(aS.filter(x=>x>0).length/aS.length*100,1):null,avg_alpha_spx_pct:round(mean(aG),3),alpha_spx_hit_rate_pct:aG.length?round(aG.filter(x=>x>0).length/aG.length*100,1):null,quality:samples<10?'INSUFFICIENT_SAMPLE':(mean(aS)||0)>0&&aS.filter(x=>x>0).length/aS.length>=.55?'PROMISING':'MIXED_OR_NEGATIVE'}}
export function summarize(signals,horizons=[1,3,5,10,20]){const groups={live:signals.filter(x=>!x.research_only),research_backfill:signals.filter(x=>x.research_only),all:signals};const summary={};for(const [k,rows] of Object.entries(groups))summary[k]={signals:rows.length,matured:rows.filter(x=>x.status==='MATURED').length,horizons:Object.fromEntries(horizons.map(h=>[`${h}D`,statsFor(rows,h)]))};const mechanisms={};for(const id of new Set(signals.map(x=>x.mechanism_id))){const rows=signals.filter(x=>x.mechanism_id===id);mechanisms[id]={signals:rows.length,live_signals:rows.filter(x=>!x.research_only).length,horizons:Object.fromEntries(horizons.map(h=>[`${h}D`,statsFor(rows,h)]))}}return {summary,mechanisms}}
