import fs from 'node:fs/promises';
import path from 'node:path';
import {collectSignals,evaluateSignal,summarize} from './backtest-core.mjs';

const read=async(p,fallback)=>JSON.parse(await fs.readFile(p,'utf8').catch(()=>JSON.stringify(fallback)));
const policy=await read('config/backtest-policy.json',{horizons:[1,3,5,10,20],basket_size:5,min_basket_coverage:.6,backfill:{enabled:true,max_history_files:300},max_signals:1500});
const seeds=await read('config/investment-seeds.json',{mechanisms:{}}),current=await read('data/current.json',{mechanisms:{},transitions:[],wave_transitions:[]}),investment=await read('data/investment-layer.json',{strategies:{}}),market=await read('data/market.json',{metrics:{},context:{}}),ledgerPath='data/backtest-ledger.json',summaryPath='data/backtest-summary.json',prior=await read(ledgerPath,{version:'1.0.0',signals:[]});
const horizons=(policy.horizons||[1,3,5,10,20]).map(Number).filter(x=>x>0),minCoverage=Number(policy.min_basket_coverage||.6),signals=[...(prior.signals||[])],byId=new Map(signals.map((x,i)=>[x.id,i]));

function enrichLive(s){const inv=investment.strategies?.[s.mechanism_id];if(!inv)return {...s,origin:'LIVE_PREREGISTERED'};const priced=Number.isFinite(Number(inv.priced_in))?Number(inv.priced_in):s.priced_in,causal=Number(s.causal_score||0);return {...s,origin:'LIVE_PREREGISTERED',priced_in:priced,causal_gap:Number.isFinite(priced)?+(causal-priced).toFixed(1):s.causal_gap,pricing_regime:inv.pricing_regime||null,pricing_confidence:inv.pricing_confidence??null,investment_action:inv.action||null,opportunity_score:inv.opportunity_score??null,transmission_score:inv.transmission_score??null}}
function upsert(s,{preferLive=false}={}){const i=byId.get(s.id);if(i==null){byId.set(s.id,signals.length);signals.push(s);return true}if(preferLive&&signals[i]?.research_only){signals[i]={...signals[i],...s,research_only:false,origin:'LIVE_PREREGISTERED'};return true}return false}

let addedLive=0,addedBackfill=0;
for(const s of collectSignals(current,{seeds,policy,researchOnly:false}))if(upsert(enrichLive(s),{preferLive:true}))addedLive++;

if(policy.backfill?.enabled!==false){
  try{const dir='data/history-v2',names=(await fs.readdir(dir)).filter(n=>/^run_.*\.json$/.test(n)).sort().slice(-Number(policy.backfill?.max_history_files||300));for(const name of names){try{const snap=JSON.parse(await fs.readFile(path.join(dir,name),'utf8'));for(const s of collectSignals(snap,{seeds,policy,researchOnly:true,sourceFile:`history-v2/${name}`})){s.origin='RESEARCH_BACKFILL';if(upsert(s))addedBackfill++}}catch{}}}catch{}
}

const evaluated=signals.map(s=>evaluateSignal(s,market,horizons,minCoverage)).sort((a,b)=>Date.parse(a.signal_at)-Date.parse(b.signal_at)).slice(-Number(policy.max_signals||1500));
const agg=summarize(evaluated,horizons),now=new Date().toISOString(),methodology={entry:'First exchange daily bar whose session timestamp is strictly after signal_at; fill at that session open.',basket:`Equal-weight first ${Number(policy.basket_size||5)} configured mechanism proxies from config/investment-seeds.json. Basket membership is frozen at signal creation.`,exits:`Close after ${horizons.join('/')} trading sessions from entry session.`,benchmarks:'Sector/theme benchmark fixed by mechanism family plus S&P 500 (^GSPC).',alpha:'Basket return minus benchmark return over the identical entry/exit session count.',live_vs_backfill:'LIVE_PREREGISTERED signals are created by scans after this feature exists. RESEARCH_BACKFILL reconstructs older transitions and is excluded from live headline statistics to prevent look-ahead claims.',sample_gate:'Performance quality remains INSUFFICIENT_SAMPLE until at least 10 completed observations at a horizon.'};
const ledger={version:'1.0.0',generated_at:now,run_id:current.run_id||market.run_id||null,policy:{horizons,basket_size:Number(policy.basket_size||5),min_basket_coverage:minCoverage,entry_rule:'NEXT_SESSION_OPEN',max_signals:Number(policy.max_signals||1500)},methodology,stats:{signals:evaluated.length,live:evaluated.filter(x=>!x.research_only).length,research_backfill:evaluated.filter(x=>x.research_only).length,pending_entry:evaluated.filter(x=>x.status==='PENDING_ENTRY').length,active:evaluated.filter(x=>x.status==='ACTIVE').length,matured:evaluated.filter(x=>x.status==='MATURED').length,added_live_this_run:addedLive,added_backfill_this_run:addedBackfill},...agg,signals:evaluated};
const recent=[...evaluated].sort((a,b)=>Date.parse(b.signal_at)-Date.parse(a.signal_at)).slice(0,16).map(s=>({id:s.id,mechanism_id:s.mechanism_id,label:s.label,signal_at:s.signal_at,origin:s.origin,status:s.status,triggers:s.triggers,causal_score:s.causal_score,priced_in:s.priced_in,causal_gap:s.causal_gap,benchmark:s.benchmark,basket:s.basket.map(x=>x.symbol),horizons:s.horizons}));
const compact={version:'1.0.0',generated_at:now,run_id:ledger.run_id,methodology,stats:ledger.stats,summary:ledger.summary,mechanisms:ledger.mechanisms,recent_signals:recent};
await fs.writeFile(ledgerPath,JSON.stringify(ledger,null,2)+'\n');await fs.writeFile(summaryPath,JSON.stringify(compact,null,2)+'\n');
const h5=ledger.summary?.live?.horizons?.['5D']||{};console.log(`backtest: live=${ledger.stats.live} backfill=${ledger.stats.research_backfill} new=${addedLive} 5D_samples=${h5.samples||0} alpha_sector=${h5.avg_alpha_sector_pct??'n/a'} quality=${h5.quality||'n/a'}`);
