import fs from 'node:fs/promises';

const current=JSON.parse(await fs.readFile('data/current.json','utf8').catch(()=>'{"mechanisms":{}}'));
const inv=JSON.parse(await fs.readFile('data/investment-layer.json','utf8').catch(()=>'{"strategies":{}}'));
const cfg=JSON.parse(await fs.readFile('config/mechanisms.json','utf8').catch(()=>'{"mechanisms":[]}'));
const path='data/daily-briefing.json';
const previous=JSON.parse(await fs.readFile(path,'utf8').catch(()=>'{}'));
const now=new Date(),date=now.toISOString().slice(0,10);
if(previous.date===date&&!process.env.GEARWATCH_FORCE_BRIEFING){console.log(`briefing: ${date} already exists`);process.exit(0)}
const KEY=process.env.OPENAI_API_KEY||'',MODEL=process.env.OPENAI_BRIEFING_MODEL||'gpt-5-nano';
const clamp=x=>Math.max(0,Math.min(100,Number(x)||0));
const lowPricing=new Set(['JAPAN_CARRY_UNWIND','CEYHAN_BYPASS','UNDERWATER_SECURITY']);
function priority(m,s){const causal=clamp(m.score),priced=clamp(s?.priced_in??m.crowd?.priced_in),tx=clamp(s?.transmission_score),timing=clamp(s?.timing_score);let v=.4*causal+.25*tx+.2*(100-priced)+.15*timing;if(lowPricing.has(m.id))v-=4;if(s?.crowd?.block_chase)v-=10;return Math.round(clamp(v))}
function warning(id,m){const w=[];if(lowPricing.has(id))w.push('El priced-in interno usa proxies de renta variable y no mide por completo el instrumento causal primario.');if(id==='CEYHAN_BYPASS'&&!(m.evidence||[]).some(e=>/ceyhan|iraq[- ]turkey|kirkuk[- ]ceyhan/i.test(`${e.claim||''} ${e.signal||''}`)))w.push('No hay evidencia viva específica de flujo por Ceyhan; no usar STS/Hormuz como sustituto.');if(m.semantic_guard?.rejected?.length)w.push(`${m.semantic_guard.rejected.length} evidencias fueron rechazadas por la guardia semántica.`);if(m.verifier?.verdict==='MIXED'||m.verifier?.verdict==='CONTRADICTED')w.push(`Verificador: ${m.verifier.verdict}.`);return w}
const rows=(cfg.mechanisms||[]).map(c=>{const m={...c,...(current.mechanisms?.[c.id]||{})},s=inv.strategies?.[c.id]||{};return{id:c.id,label:c.label,state:m.state||'UNKNOWN',causal:Number(m.score||0),priced_in:Number(s.priced_in??m.crowd?.priced_in??0),pricing_confidence:lowPricing.has(c.id)?'LOW':'HIGH',transmission:Number(s.transmission_score||0),timing:Number(s.timing_score||0),action:s.action||'RESEARCH_ONLY',wave:s.wave_phase||m.crowd?.phase||'DISCOVERY',priority:priority(m,s),summary:m.summary||'',warnings:warning(c.id,m),evidence:(m.evidence||[]).slice(0,6).map(e=>({phase:e.phase,signal:e.signal,claim:e.claim,source:e.source_domain||e.source_name,grade:e.source_grade})),pieces:(s.top5||[]).slice(0,5).map(x=>({symbol:x.symbol,ret20:x.market?.ret20,tx:x.transmission?.score})),next:(m.expected_next||s.trigger||[]).slice(0,4)}}).sort((a,b)=>b.priority-a.priority||b.causal-a.causal);
const top=rows.slice(0,12),notes=Object.fromEntries(top.map(x=>[x.id,`${x.label}: causal ${Math.round(x.causal)}/100; priced-in interno ${Math.round(x.priced_in)}/100; confianza pricing ${x.pricing_confidence}. ${x.warnings.join(' ')}`]));
const base={version:'4.1.0',date,generated_at:now.toISOString(),model:'deterministic-fallback',cost_usd:0,judge_health:{status:KEY?'DEGRADED_FALLBACK':'NO_KEY',schema_version:'4.1.0'},headline:`GearWatch: ${top.slice(0,3).map(x=>x.label).join(', ')}`,briefing:'Radar causal: prioriza mecanismos físicos y separa madurez causal de lo que realmente puede medirse como descontado por el mercado.',root_drivers:[],butterflies:top.slice(0,5).map(x=>({mechanism_id:x.id,label:x.label,thesis:x.summary||`Madurez causal ${x.causal}/100.`,pieces:x.pieces.map(p=>p.symbol),why_unpriced:x.pricing_confidence==='LOW'?'Pricing incompleto: no afirmar que el mercado lo ignora.':x.priced_in<25?'Pricing observado bajo en las piezas asociadas.':'Parte del movimiento ya es visible.',watch_next:x.next[0]||'Esperar confirmación adicional.'})),already_moved:top.filter(x=>x.priced_in>=50||x.pieces.some(p=>Number(p.ret20)>15)).slice(0,5).map(x=>({mechanism_id:x.id,label:x.label,reason:'Movimiento/pricing ya material; no confundir una tesis correcta con una señal temprana.'})),blindspots:rows.filter(x=>x.warnings.length).slice(0,6).map(x=>({mechanism_id:x.id,label:x.label,reason:x.warnings.join(' ')})),watch_today:top.slice(0,6).map(x=>({mechanism_id:x.id,title:x.label,reason:x.next[0]||'Buscar nueva confirmación causal.'})),mechanism_notes:notes};
if(!KEY){await fs.writeFile(path,JSON.stringify(base,null,2)+'\n');process.exit(0)}

// Strict Structured Outputs: every object with properties must require every key.
// Dynamic mechanism_notes is appended after model generation, never included in schema.
const schema={type:'object',additionalProperties:false,properties:{headline:{type:'string'},briefing:{type:'string'},root_drivers:{type:'array',items:{type:'object',additionalProperties:false,properties:{name:{type:'string'},why_now:{type:'string'},mechanisms:{type:'array',items:{type:'string'}}},required:['name','why_now','mechanisms']}},butterflies:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},label:{type:'string'},thesis:{type:'string'},pieces:{type:'array',items:{type:'string'}},why_unpriced:{type:'string'},watch_next:{type:'string'}},required:['mechanism_id','label','thesis','pieces','why_unpriced','watch_next']}},already_moved:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},label:{type:'string'},reason:{type:'string'}},required:['mechanism_id','label','reason']}},blindspots:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},label:{type:'string'},reason:{type:'string'}},required:['mechanism_id','label','reason']}},watch_today:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},title:{type:'string'},reason:{type:'string'}},required:['mechanism_id','title','reason']}}},required:['headline','briefing','root_drivers','butterflies','already_moved','blindspots','watch_today']};
function validate(node,p='$'){if(!node||typeof node!=='object')return;if(node.type==='object'&&node.properties){const keys=Object.keys(node.properties),req=node.required||[];if(node.additionalProperties!==false||keys.some(k=>!req.includes(k))||keys.length!==req.length)throw new Error(`invalid strict schema at ${p}`);for(const [k,v] of Object.entries(node.properties))validate(v,`${p}.${k}`)}if(node.type==='array')validate(node.items,`${p}[]`)}
validate(schema);
const prompt=`Escribe el briefing diario de GearWatch en español natural. No es un screener. Explica causas raíz, madurez causal frente a pricing, mariposas, piezas empresariales, qué ya ha corrido, contradicciones/sensores ciegos y qué vigilar. No inventes hechos. No des órdenes de inversión. Si pricing_confidence=LOW, NO digas que algo está poco descontado: explica que el sensor es incompleto. Respeta warnings y no uses evidencia semánticamente rechazada. SNAPSHOT=${JSON.stringify(top)}`;
try{const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,max_completion_tokens:1800,messages:[{role:'system',content:'Eres un juez editorial independiente, escéptico y estrictamente ligado a la evidencia.'},{role:'user',content:prompt}],response_format:{type:'json_schema',json_schema:{name:'gearwatch_daily_briefing',strict:true,schema}}}),signal:AbortSignal.timeout(60000)});const text=await r.text();if(!r.ok)throw new Error(`OpenAI ${r.status}: ${text.slice(0,500)}`);const j=JSON.parse(text),parsed=JSON.parse(j.choices?.[0]?.message?.content||'{}'),u=j.usage||{},cost=(Number(u.prompt_tokens||0)*.05+Number(u.completion_tokens||0)*.40)/1e6;const final={version:'4.1.0',date,generated_at:now.toISOString(),model:j.model||MODEL,cost_usd:+cost.toFixed(6),usage:u,judge_health:{status:'OK',schema_version:'4.1.0'},...parsed,mechanism_notes:notes};await fs.writeFile(path,JSON.stringify(final,null,2)+'\n');console.log(`briefing: ${date} ${final.model} judge=OK cost=$${final.cost_usd}`)}catch(e){base.error=String(e.message||e);base.judge_health.status='DEGRADED_FALLBACK';await fs.writeFile(path,JSON.stringify(base,null,2)+'\n');console.error(`briefing fallback: ${base.error}`)}
