import fs from 'node:fs/promises';
const current=JSON.parse(await fs.readFile('data/current.json','utf8').catch(()=>'{"mechanisms":{}}'));
const inv=JSON.parse(await fs.readFile('data/investment-layer.json','utf8').catch(()=>'{"strategies":{}}'));
const cfg=JSON.parse(await fs.readFile('config/mechanisms.json','utf8').catch(()=>'{"mechanisms":[]}'));
const path='data/daily-briefing.json';
const previous=JSON.parse(await fs.readFile(path,'utf8').catch(()=>'{}'));
const now=new Date(),date=now.toISOString().slice(0,10);
if(previous.date===date&&!process.env.GEARWATCH_FORCE_BRIEFING){console.log(`briefing: ${date} already exists; preserving one-call-per-day budget`);process.exit(0)}
const KEY=process.env.OPENAI_API_KEY||'',MODEL=process.env.OPENAI_BRIEFING_MODEL||process.env.OPENAI_INVESTMENT_MODEL||'gpt-5-nano';
const clamp=x=>Math.max(0,Math.min(100,Number(x)||0));
const ROOT={DIESEL_REFINING_CRISIS:'Hormuz / energía',PRODUCT_TANKER_TONMILES:'Hormuz / logística',CRUDE_TANKER_DISLOCATION:'Hormuz / logística',ATLANTIC_BARREL_PREMIUM:'Hormuz / energía',CEYHAN_BYPASS:'Rutas alternativas',LNG_REROUTING:'Hormuz / LNG',OIL_SERVICE_CAPEX_SECOND_WAVE:'Hormuz / energía',ARSENAL_DEPLETION:'Ucrania + Irán + rearme',ROCKET_MOTOR_SHORTAGE:'Ucrania + Irán + rearme',ENERGETICS_SHORTAGE:'Ucrania + Irán + rearme',CHEAP_DRONE_SCALING:'Ucrania + Irán + rearme',COUNTER_UAS_COST_CURVE:'Ucrania + Irán + rearme',UNDERWATER_SECURITY:'Infraestructura crítica',MILITARY_ENERGY_AUTONOMY:'Ucrania + Irán + rearme',EUROPE_STRATEGIC_AUTONOMY:'Ucrania + Irán + rearme',AI_TIME_TO_POWER:'IA / electricidad',AI_GHOST_DEMAND:'IA / electricidad',BEHIND_METER_AI_POWER:'IA / electricidad',ROBOTICS_ACTUATOR_SCALE:'Robótica física',ROBOTICS_DECOUPLING:'Robótica física',STRATEGIC_ALUMINIUM:'Materiales estratégicos',RARE_EARTH_MAGNET_SHORTAGE:'Materiales estratégicos',NUCLEAR_FUEL_SOVEREIGNTY:'Materiales estratégicos',JAPAN_CARRY_UNWIND:'Liquidez global',GLOBAL_REFINANCING_STRESS:'Liquidez global',OT_CYBER_SHOCK:'Infraestructura crítica'};
function butterfly(m,s){const causal=clamp(m.score),priced=clamp(s?.priced_in??m.crowd?.priced_in),tx=clamp(s?.transmission_score),timing=clamp(s?.timing_score),delta=Number(m.score_delta||0),change=clamp(50+delta*3),gate=.45+.55*Math.min(1,causal/55);let v=(.38*causal+.25*tx+.20*(100-priced)+.10*change+.07*timing)*gate;if(['PREPARE','SCOUT_WINDOW'].includes(s?.action))v+=5;if(['PRE_WAVE','EARLY_WAVE'].includes(s?.wave_phase))v+=4;if(s?.crowd?.block_chase)v-=10;return Math.round(clamp(v))}
const rows=(cfg.mechanisms||[]).map(c=>{const m={...c,...(current.mechanisms?.[c.id]||{})},s=inv.strategies?.[c.id]||{};return {id:c.id,label:c.label,root:ROOT[c.id]||'Otros',state:m.state||'UNKNOWN',causal:Number(m.score||0),delta:Number(m.score_delta||0),priced_in:Number(s.priced_in??m.crowd?.priced_in??0),transmission:Number(s.transmission_score||0),timing:Number(s.timing_score||0),action:s.action||'RESEARCH_ONLY',wave:s.wave_phase||m.crowd?.phase||'DISCOVERY',priority:butterfly(m,s),summary:m.summary||'',evidence:(m.evidence||[]).slice(0,6).map(e=>({phase:e.phase,signal:e.signal,claim:e.claim,source:e.source_domain||e.source_name,grade:e.source_grade})),pieces:(s.top5||[]).slice(0,5).map(x=>({symbol:x.symbol,exposure:x.exposure,tx:x.transmission?.score,ret20:x.market?.ret20,rel20:x.market?.rel20})),next:(m.expected_next||s.trigger||[]).slice(0,4),invalidation:(m.invalidation||s.invalidation||[]).slice(0,3),sensor_rescue:Boolean(m.rescue||false)}}).sort((a,b)=>b.priority-a.priority||b.causal-a.causal);
const top=rows.slice(0,12);
const deterministic={version:'4.0.0',date,generated_at:now.toISOString(),model:'deterministic-fallback',cost_usd:0,headline:`El jardín se concentra en ${top.slice(0,3).map(x=>x.label).join(', ')}`,briefing:'Los mecanismos se ordenan por madurez causal, transmisión a empresas, cambio reciente y cuánto parece haber descontado ya el mercado. El objetivo no es predecir retornos pequeños: es detectar cuellos físicos o logísticos antes de que se conviertan en consenso.',root_drivers:[...new Set(top.map(x=>x.root))].slice(0,5).map(name=>({name,why_now:`${top.filter(x=>x.root===name&&x.causal>=25).length} engranajes con evidencia relevante`,mechanisms:top.filter(x=>x.root===name).slice(0,4).map(x=>x.id)})),butterflies:top.slice(0,5).map(x=>({mechanism_id:x.id,label:x.label,thesis:x.summary||`${x.root}: mecanismo ${x.state.toLowerCase()} con madurez causal ${Math.round(x.causal)}/100 y descuento estimado ${Math.round(x.priced_in)}/100.`,pieces:x.pieces.slice(0,4).map(p=>p.symbol),why_unpriced:x.priced_in<25?'El crowd/pricing sigue bajo.':'Parte del movimiento ya está visible.',watch_next:x.next[0]||'Esperar nueva confirmación física.'})),already_moved:top.filter(x=>x.priced_in>=50||x.pieces.some(p=>Number(p.ret20)>15)).slice(0,4).map(x=>({mechanism_id:x.id,label:x.label,reason:`Priced-in ${Math.round(x.priced_in)}/100 o piezas con movimiento fuerte.`})),blindspots:rows.filter(x=>(x.causal===0&&x.summary==='')||(x.id==='COUNTER_UAS_COST_CURVE'&&x.causal<25)).slice(0,4).map(x=>({mechanism_id:x.id,label:x.label,reason:'Hay candidatos o una tesis relevante, pero la evidencia validada sigue demasiado débil; tratarlo como sensor a revisar, no como señal de compra.'})),watch_today:top.slice(0,6).map(x=>({mechanism_id:x.id,title:x.label,reason:x.next[0]||`Buscar confirmación de ${x.root}.`})),mechanism_notes:Object.fromEntries(top.map(x=>[x.id,`${x.label}: causal ${Math.round(x.causal)}/100 frente a mercado descontado ${Math.round(x.priced_in)}/100. ${x.summary||'La cadena aún necesita confirmación.'}`]))};
if(!KEY){await fs.writeFile(path,JSON.stringify(deterministic,null,2)+'\n');console.log('briefing: OPENAI_API_KEY missing; deterministic daily briefing written');process.exit(0)}
const schema={type:'object',additionalProperties:false,properties:{headline:{type:'string'},briefing:{type:'string'},root_drivers:{type:'array',items:{type:'object',additionalProperties:false,properties:{name:{type:'string'},why_now:{type:'string'},mechanisms:{type:'array',items:{type:'string'}}},required:['name','why_now','mechanisms']}},butterflies:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},label:{type:'string'},thesis:{type:'string'},pieces:{type:'array',items:{type:'string'}},why_unpriced:{type:'string'},watch_next:{type:'string'}},required:['mechanism_id','label','thesis','pieces','why_unpriced','watch_next']}},already_moved:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},label:{type:'string'},reason:{type:'string'}},required:['mechanism_id','label','reason']}},blindspots:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},label:{type:'string'},reason:{type:'string'}},required:['mechanism_id','label','reason']}},watch_today:{type:'array',items:{type:'object',additionalProperties:false,properties:{mechanism_id:{type:'string'},title:{type:'string'},reason:{type:'string'}},required:['mechanism_id','title','reason']}},mechanism_notes:{type:'object',additionalProperties:{type:'string'}}},required:['headline','briefing','root_drivers','butterflies','already_moved','blindspots','watch_today','mechanism_notes']};
const prompt=`Escribe el briefing diario editorial de GearWatch en español natural. GearWatch es un jardín de mariposas causal, NO un screener de retornos. Explica: 1) qué causas raíz mueven hoy varios engranajes; 2) qué mecanismos tienen una brecha interesante entre evidencia causal y descuento del mercado; 3) qué piezas empresariales reciben el impacto; 4) qué ya ha corrido y no debe perseguirse; 5) sensores ciegos o contradicciones; 6) qué hay que observar en el próximo ciclo. No inventes hechos. No des órdenes de compra/venta ni objetivos de precio. Usa únicamente SNAPSHOT. Sé incisivo y comprensible para una persona no cuantitativa. Máximo 900 palabras.\nSNAPSHOT=${JSON.stringify(top)}`;
try{const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:MODEL,max_completion_tokens:1800,messages:[{role:'system',content:'Eres el juez editorial independiente de un radar causal de mercados. Tu trabajo es traducir evidencia estructurada a lenguaje humano sin perder cautela ni inventar datos.'},{role:'user',content:prompt}],response_format:{type:'json_schema',json_schema:{name:'gearwatch_daily_briefing',strict:true,schema}}}),signal:AbortSignal.timeout(60000)});const text=await r.text();if(!r.ok)throw new Error(`OpenAI ${r.status}: ${text.slice(0,200)}`);const j=JSON.parse(text),parsed=JSON.parse(j.choices?.[0]?.message?.content||'{}'),u=j.usage||{},cost=(Number(u.prompt_tokens||0)*.05+Number(u.completion_tokens||0)*.40)/1e6;const final={version:'4.0.0',date,generated_at:now.toISOString(),model:j.model||MODEL,cost_usd:+cost.toFixed(6),usage:u,...parsed};await fs.writeFile(path,JSON.stringify(final,null,2)+'\n');console.log(`briefing: ${date} written with ${final.model}; cost=$${final.cost_usd.toFixed(6)}`)}catch(e){deterministic.error=String(e.message||e);await fs.writeFile(path,JSON.stringify(deterministic,null,2)+'\n');console.log(`briefing: model failed, deterministic fallback written: ${deterministic.error}`)}
