import fs from 'node:fs/promises';

const read=async(path,fallback)=>JSON.parse(await fs.readFile(path,'utf8').catch(()=>JSON.stringify(fallback)));
const current=await read('data/current.json',{mechanisms:{}}),investment=await read('data/investment-layer.json',{strategies:{},summary:{}}),briefing=await read('data/daily-briefing.json',{}),pricing=await read('data/pricing-sensors.json',{coverage:{},mechanisms:{},observations:{}});
const failures=[],warnings=[],mechanisms=Object.values(current.mechanisms||{}),strategies=Object.values(investment.strategies||{});
if(mechanisms.length<20)failures.push(`current.json contains only ${mechanisms.length} mechanisms`);if(strategies.length<20)failures.push(`investment-layer.json contains only ${strategies.length} strategies`);if(Number(investment.summary?.candidate_rows||0)<=0)failures.push('investment-layer.json has zero candidate rows');if(!current.run_id)failures.push('current.json has no run_id');if(investment.run_id&&current.run_id&&investment.run_id!==current.run_id)failures.push(`investment/current run mismatch: ${investment.run_id} != ${current.run_id}`);
const ceyhan=current.mechanisms?.CEYHAN_BYPASS;if(ceyhan){const bad=(ceyhan.evidence||[]).filter(e=>e?.valid!==false&&!/ceyhan|iraq[- ]turkey|kirkuk[- ]ceyhan|kurdistan.{0,45}pipeline|pipeline.{0,45}(turkey|ceyhan)/i.test(`${e.signal||''} ${e.claim||''}`));if(bad.length)warnings.push(`CEYHAN semantic contamination detected in ${bad.length} live evidence items`)}
if(briefing.error){warnings.push(`briefing fallback: ${String(briefing.error).slice(0,180)}`);if(/invalid schema|response_format|strict schema/i.test(String(briefing.error)))failures.push('briefing judge failed because of a schema error')}if(process.env.OPENAI_API_KEY&&briefing.model==='deterministic-fallback'&&!briefing.error)warnings.push('OpenAI configured but briefing is deterministic fallback');if(briefing.judge_health?.status==='OK'&&briefing.error)failures.push('judge_health says OK while briefing contains error');
const requiredBlocks=['ais_hormuz','eia','mof_japan','us_procurement','cftc','ukmto','entsoe','comtrade'],blocks=pricing.coverage?.blocks||{};for(const b of requiredBlocks)if(!(b in blocks))failures.push(`pricing block missing: ${b}`);if(Object.keys(pricing.mechanisms||{}).length<20)failures.push(`pricing-sensors covers only ${Object.keys(pricing.mechanisms||{}).length} mechanisms`);
const fatalPricing=Object.entries(pricing.observations||{}).filter(([,x])=>x.status==='ERROR');if(fatalPricing.length)warnings.push(`pricing sources erroring: ${fatalPricing.map(([k])=>k).join(', ')}`);const notConfigured=Object.entries(pricing.observations||{}).filter(([,x])=>x.status==='NOT_CONFIGURED');if(notConfigured.length)warnings.push(`pricing sources awaiting keys: ${notConfigured.map(([k])=>k).join(', ')}`);if(Number(pricing.coverage?.live_sources||0)===0)warnings.push('no live primary pricing source observed in this cycle');
const sports=/\b(parlay|nba|nfl|mlb|nhl|ncaa|wnba|soccer|football|basketball|baseball|hockey|tennis|golf|ufc|match|touchdown|innings?|moneyline)\b/i;const contaminated=[];for(const [id,m] of Object.entries(pricing.observations?.KALSHI?.mechanisms||{}))for(const h of m.hits||[])if(sports.test(`${h.title||''} ${h.ticker||''}`))contaminated.push(`${id}:${h.ticker||h.title}`);if(contaminated.length)failures.push(`Kalshi semantic contamination survived guard: ${contaminated.slice(0,4).join(', ')}`);
const impossible=Object.entries(investment.strategies||{}).filter(([,s])=>s.pricing_regime==='PRIMARY_PRICED_EQUITY_BLIND'&&Number(s.pricing_confidence||0)<25);if(impossible.length)failures.push(`high-conviction pricing regime assigned with low confidence: ${impossible.map(([id])=>id).slice(0,5).join(', ')}`);
const health={checked_at:new Date().toISOString(),run_id:current.run_id||null,status:failures.length?'FAIL':warnings.length?'DEGRADED':'OK',mechanisms:mechanisms.length,strategies:strategies.length,candidate_rows:Number(investment.summary?.candidate_rows||0),judge:briefing.judge_health||{status:briefing.model==='deterministic-fallback'?'DEGRADED_FALLBACK':'UNKNOWN'},pricing:{version:pricing.version||null,live_sources:Number(pricing.coverage?.live_sources||0),scored_sources:Number(pricing.coverage?.scored_sources||0),blocks,quality:pricing.coverage?.quality||{}},failures,warnings};await fs.writeFile('data/production-health.json',JSON.stringify(health,null,2)+'\n');console.log(`healthcheck: ${health.status} mechanisms=${health.mechanisms} strategies=${health.strategies} candidates=${health.candidate_rows} pricing_live=${health.pricing.live_sources}`);for(const w of warnings)console.warn(`health warning: ${w}`);if(failures.length){for(const f of failures)console.error(`health failure: ${f}`);process.exit(1)}
