import fs from 'node:fs/promises';

const seeds=JSON.parse(await fs.readFile('config/investment-seeds.json','utf8'));
const cfg=JSON.parse(await fs.readFile('config/mechanisms.json','utf8'));
const current=JSON.parse(await fs.readFile('data/current.json','utf8').catch(()=>'{"mechanisms":{}}'));
const market=JSON.parse(await fs.readFile('data/market.json','utf8').catch(()=>'{"metrics":{},"context":{}}'));
const broker=JSON.parse(await fs.readFile('data/broker.json','utf8').catch(()=>'{"authoritative":false,"instruments":{}}'));
const budgetPath='data/budget.json',budget=JSON.parse(await fs.readFile(budgetPath,'utf8').catch(()=>'{"days":{}}'));
const OPENAI_KEY=process.env.OPENAI_API_KEY||'';
const OPENAI_MODEL=process.env.OPENAI_INVESTMENT_MODEL||'gpt-5-nano';
const now=new Date(),day=now.toISOString().slice(0,10);budget.days[day]??={};budget.days[day].openai_jury_calls??=0;budget.days[day].openai_jury_usd??=0;
const JURY_CALL_CAP=4,JURY_USD_CAP=.01;
const clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const benchFor=id=>/DIESEL|TANKER|CRUDE|ATLANTIC|CEYHAN|LNG|OIL_SERVICE/.test(id)?'XLE':/ARSENAL|ROCKET|ENERGETICS|DRONE|COUNTER_UAS|UNDERWATER|MILITARY|EUROPE_STRATEGIC/.test(id)?'ITA':/AI_|ROBOTICS|CYBER/.test(id)?'QQQ':/JAPAN/.test(id)?'EWJ':/NUCLEAR/.test(id)?'URA':/RARE_EARTH|ALUMINIUM/.test(id)?'XME':/REFINANCING/.test(id)?'IWM':'^GSPC';
const t212Url=s=>broker.instruments?.[s]?.broker_url||`https://www.trading212.com/es/trading-instruments/invest/${s.includes('.')?s.replace('.L','.GB').replace('.MI','.IT').replace('.PA','.FR'):`${s}.US`}`;
function marketScore(symbol,benchTicker){const x=market.metrics?.[symbol],b=market.context?.[benchTicker]||market.context?.['^GSPC'];if(!x)return {score:42,quality:'NO_MARKET',rel5:null,rel20:null,rel2h:null};const rel5=Number.isFinite(x.ret5)?x.ret5-(Number(b?.ret5)||0):0,rel20=Number.isFinite(x.ret20)?x.ret20-(Number(b?.ret20)||0):0,rel2h=Number.isFinite(x.intraday?.ret2h)?x.intraday.ret2h-(Number(b?.intraday?.ret2h)||0):0,trend=(x.above20?7:-3)+(x.above50?7:-3)+(x.above200?5:0),vz=Number(x.volumeZ||0);return {score:Math.round(clamp(50+rel5*4+rel20*1.4+rel2h*5+vz*3+trend)),quality:'LIVE',price:x.price??null,ret1:x.ret1??null,ret5:x.ret5??null,ret20:x.ret20??null,rel5:+rel5.toFixed(2),rel20:+rel20.toFixed(2),rel2h:+rel2h.toFixed(2),volumeZ:vz,above20:x.above20??null,above50:x.above50??null,above200:x.above200??null};}
function actionFor(m){if(m.state==='INVALIDATED')return 'INVALIDATED';if(m.state==='SATURATED')return 'DO_NOT_CHASE';if(m.state==='ACTIVE'&&m.alpha?.eligible)return 'DEPLOY_WINDOW';if(m.state==='ACTIVE')return 'WAIT_ALPHA_GATE';if(m.state==='ARMING')return 'PREPARE';if(m.state==='WATCH')return 'WATCH';if(m.state==='STALE')return 'STALE_RECHECK';return 'RESEARCH_ONLY'}
function pie(rows){if(!rows.length)return[];const raw=rows.map(x=>Math.max(1,x.rank_score-35)),sum=raw.reduce((a,b)=>a+b,0);let weights=raw.map(x=>Math.round(x/sum*100)),delta=100-weights.reduce((a,b)=>a+b,0);for(let i=0;delta!==0;i=(i+1)%weights.length){weights[i]+=delta>0?1:-1;delta+=delta>0?-1:1}return rows.map((x,i)=>({symbol:x.symbol,weight:weights[i]}))}
const out={version:'2.6.0',generated_at:now.toISOString(),run_id:current.run_id||market.run_id||null,broker:{mode:broker.mode||'UNVERIFIED',authoritative:Boolean(broker.authoritative),credentials_configured:Boolean(broker.credentials_configured),verified:broker.stats?.verified||0,available:broker.stats?.available||0},openai_jury:{configured:Boolean(OPENAI_KEY),model:OPENAI_MODEL,calls_before:budget.days[day].openai_jury_calls,usd_before:budget.days[day].openai_jury_usd,call_cap:JURY_CALL_CAP,usd_cap:JURY_USD_CAP},strategies:{},summary:{strategies:0,deploy_window:0,prepare:0,watch:0,broker_verified:0,clean_long_shortage:0}};
for(const m of cfg.mechanisms){const cur=current.mechanisms?.[m.id]||{state:'UNKNOWN',score:0,market:{score:0,crowding:0},alpha:{eligible:false},evidence:[],expected_next:[],invalidation:[]},bench=benchFor(m.id),rows=[];for(const seed of seeds.mechanisms?.[m.id]||[]){const [symbol,fit,exposure]=seed,br=broker.instruments?.[symbol]||{},available=broker.authoritative?br.available===true:true;if(!available)continue;const ms=marketScore(symbol,bench),rank=Math.round(clamp(.67*fit+.23*ms.score+.10*(exposure==='DIRECT'?100:48)));rows.push({symbol,name:br.name||br.short_name||symbol,exposure,fit,rank_score:rank,market:ms,broker_verified:Boolean(br.verified),broker_available:br.available??null,broker_url:t212Url(symbol),t212_ticker:br.t212_ticker||null,isin:br.isin||null,currency:br.currency||null,exchange:br.exchange||null})}rows.sort((a,b)=>b.rank_score-a.rank_score||b.fit-a.fit);const top=rows.slice(0,5),clean=top.filter(x=>x.exposure==='DIRECT'&&x.fit>=75).length,action=actionFor(cur),opportunity=Math.round(clamp(.45*(cur.score||0)+.25*(cur.market?.score||0)+.30*(top.length?top.reduce((a,x)=>a+x.rank_score,0)/top.length:0))),strategy={id:m.id,label:m.label,tier:m.tier,state:cur.state||'UNKNOWN',action,opportunity_score:opportunity,causal_score:cur.score||0,market_score:cur.market?.score||0,crowding:cur.market?.crowding||0,alpha:cur.alpha||{eligible:false},benchmark:bench,top5:top,model_pie:pie(top),clean_direct_count:clean,quality:clean>=4?'CLEAN':clean>=2?'MIXED':'WEAK',broker_strict:Boolean(broker.authoritative),deployable:Boolean(broker.authoritative&&action==='DEPLOY_WINDOW'&&clean>=2),summary:cur.summary||'',trigger:(cur.expected_next||[]).slice(0,4),invalidation:(cur.invalidation||[]).slice(0,4),alpha_blockers:cur.alpha?.reasons||[],jury:null};if(top.length<5)strategy.warning=`Only ${top.length} broker-eligible seed companies remain.`;if(!broker.authoritative)strategy.warning='Trading 212 availability is not yet authoritative; configure read-only broker metadata credentials before treating the basket as investable.';if(clean<3)strategy.exposure_warning='Fewer than three high-fit direct long exposures; do not manufacture a five-stock basket from weak proxies.';out.strategies[m.id]=strategy}
const priority=Object.values(out.strategies).filter(x=>['DEPLOY_WINDOW','WAIT_ALPHA_GATE','PREPARE'].includes(x.action)).sort((a,b)=>b.opportunity_score-a.opportunity_score).slice(0,JURY_CALL_CAP);
const jurySchema={type:'object',additionalProperties:false,properties:{verdict:{type:'string',enum:['CLEAN','MIXED','WEAK']},note:{type:'string'},weakest_link:{type:'string'},candidate_notes:{type:'array',items:{type:'object',additionalProperties:false,properties:{symbol:{type:'string'},reason:{type:'string'},risk:{type:'string'}},required:['symbol','reason','risk']}}},required:['verdict','note','weakest_link','candidate_notes']};
async function jury(strategy){if(!OPENAI_KEY||budget.days[day].openai_jury_calls>=JURY_CALL_CAP||budget.days[day].openai_jury_usd>=JURY_USD_CAP)return null;const evidence=(current.mechanisms?.[strategy.id]?.evidence||[]).slice(0,10).map(x=>({phase:x.phase,signal:x.signal,claim:x.claim,source_grade:x.source_grade}));const candidates=strategy.top5.map(x=>({symbol:x.symbol,exposure:x.exposure,fit:x.fit,rank_score:x.rank_score,market:x.market}));const prompt=`Audit an already deterministic investment mapping. Do NOT decide whether the mechanism is active and do NOT browse. Explain why each candidate is or is not a clean equity expression of the mechanism using only the supplied mechanism description, evidence and market telemetry. Do not invent company facts. If evidence is insufficient, say so.\nMECHANISM=${strategy.id} ${strategy.label}\nSTATE=${strategy.state} causal=${strategy.causal_score} market=${strategy.market_score}\nEVIDENCE=${JSON.stringify(evidence)}\nCANDIDATES=${JSON.stringify(candidates)}`;try{const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:OPENAI_MODEL,temperature:0,max_completion_tokens:1000,messages:[{role:'system',content:'You are an independent portfolio-mapping auditor. No web search. No investment orders. Be concise and evidence-bound.'},{role:'user',content:prompt}],response_format:{type:'json_schema',json_schema:{name:'gearwatch_investment_jury',strict:true,schema:jurySchema}}}),signal:AbortSignal.timeout(45000)}),text=await r.text();if(!r.ok)throw new Error(`OpenAI ${r.status}: ${text.slice(0,180)}`);const j=JSON.parse(text),parsed=JSON.parse(j.choices?.[0]?.message?.content||'{}'),u=j.usage||{},cost=(Number(u.prompt_tokens||0)*.05+Number(u.completion_tokens||0)*.40)/1e6;budget.days[day].openai_jury_calls++;budget.days[day].openai_jury_usd=+(budget.days[day].openai_jury_usd+cost).toFixed(6);return {...parsed,model:j.model||OPENAI_MODEL,usage:u,cost_usd:+cost.toFixed(6)}}catch(e){return {error:String(e.message||e)}}}
for(const s of priority)s.jury=await jury(s);
out.openai_jury.calls_after=budget.days[day].openai_jury_calls;out.openai_jury.usd_after=budget.days[day].openai_jury_usd;const vals=Object.values(out.strategies);out.summary.strategies=vals.length;out.summary.deploy_window=vals.filter(x=>x.action==='DEPLOY_WINDOW').length;out.summary.prepare=vals.filter(x=>x.action==='PREPARE').length;out.summary.watch=vals.filter(x=>x.action==='WATCH').length;out.summary.broker_verified=vals.filter(x=>x.broker_strict).length;out.summary.clean_long_shortage=vals.filter(x=>x.clean_direct_count<3).length;
await fs.writeFile('data/investment-layer.json',JSON.stringify(out,null,2)+'\n');await fs.writeFile(budgetPath,JSON.stringify(budget,null,2)+'\n');
console.log(`investment: strategies=${vals.length} broker=${out.broker.mode} deploy=${out.summary.deploy_window} prepare=${out.summary.prepare} jury=${out.openai_jury.calls_after-out.openai_jury.calls_before} $${Number(out.openai_jury.usd_after-out.openai_jury.usd_before).toFixed(6)}`);
