import fs from 'node:fs/promises';

const seeds=JSON.parse(await fs.readFile('config/investment-seeds.json','utf8'));
const cfg=JSON.parse(await fs.readFile('config/mechanisms.json','utf8'));
const current=JSON.parse(await fs.readFile('data/current.json','utf8').catch(()=>'{"mechanisms":{}}'));
const market=JSON.parse(await fs.readFile('data/market.json','utf8').catch(()=>'{"metrics":{},"context":{}}'));
const broker=JSON.parse(await fs.readFile('data/broker.json','utf8').catch(()=>'{"instruments":{}}'));
const tx=JSON.parse(await fs.readFile('data/transmission-layer.json','utf8').catch(()=>'{"mechanisms":{}}'));
const budgetPath='data/budget.json',budget=JSON.parse(await fs.readFile(budgetPath,'utf8').catch(()=>'{"days":{}}'));
const OPENAI_KEY=process.env.OPENAI_API_KEY||'',OPENAI_MODEL=process.env.OPENAI_INVESTMENT_MODEL||'gpt-5-nano';
const now=new Date(),day=now.toISOString().slice(0,10);budget.days[day]??={};budget.days[day].openai_jury_calls??=0;budget.days[day].openai_jury_usd??=0;
const JURY_CALL_CAP=4,JURY_USD_CAP=.01,clamp=(x,a=0,b=100)=>Math.max(a,Math.min(b,x));
const benchFor=id=>/DIESEL|TANKER|CRUDE|ATLANTIC|CEYHAN|LNG|OIL_SERVICE/.test(id)?'XLE':/ARSENAL|ROCKET|ENERGETICS|DRONE|COUNTER_UAS|UNDERWATER|MILITARY|EUROPE_STRATEGIC/.test(id)?'ITA':/AI_|ROBOTICS|CYBER/.test(id)?'QQQ':/JAPAN/.test(id)?'EWJ':/NUCLEAR/.test(id)?'URA':/RARE_EARTH|ALUMINIUM/.test(id)?'XME':/REFINANCING/.test(id)?'IWM':'^GSPC';
function marketScore(symbol,benchTicker){const x=market.metrics?.[symbol],b=market.context?.[benchTicker]||market.context?.['^GSPC'];if(!x)return {score:42,quality:'NO_MARKET',rel5:null,rel20:null,rel2h:null};const rel5=Number.isFinite(x.ret5)?x.ret5-(Number(b?.ret5)||0):0,rel20=Number.isFinite(x.ret20)?x.ret20-(Number(b?.ret20)||0):0,rel2h=Number.isFinite(x.intraday?.ret2h)?x.intraday.ret2h-(Number(b?.intraday?.ret2h)||0):0,trend=(x.above20?7:-3)+(x.above50?7:-3)+(x.above200?5:0),vz=Number(x.volumeZ||0);return {score:Math.round(clamp(50+rel5*4+rel20*1.4+rel2h*5+vz*3+trend)),quality:'LIVE',price:x.price??null,ret1:x.ret1??null,ret5:x.ret5??null,ret20:x.ret20??null,rel5:+rel5.toFixed(2),rel20:+rel20.toFixed(2),rel2h:+rel2h.toFixed(2),volumeZ:vz,above20:x.above20??null,above50:x.above50??null,above200:x.above200??null}}
function actionFor(m){if(m.state==='INVALIDATED')return 'INVALIDATED';if(m.state==='SATURATED'||m.crowd?.block_chase)return 'DO_NOT_CHASE';if(m.state==='ACTIVE'&&m.alpha?.eligible)return 'DEPLOY_WINDOW';if(m.scout?.eligible)return 'SCOUT_WINDOW';if(m.state==='ACTIVE')return 'WAIT_ALPHA_GATE';if(m.state==='ARMING')return 'PREPARE';if(m.state==='WATCH')return 'WATCH';if(m.state==='STALE')return 'STALE_RECHECK';return 'RESEARCH_ONLY'}
function pie(rows){if(!rows.length)return[];const raw=rows.map(x=>Math.max(1,x.rank_score-35)),sum=raw.reduce((a,b)=>a+b,0);let weights=raw.map(x=>Math.round(x/sum*100)),delta=100-weights.reduce((a,b)=>a+b,0);for(let i=0;delta!==0;i=(i+1)%weights.length){weights[i]+=delta>0?1:-1;delta+=delta>0?-1:1}return rows.map((x,i)=>({symbol:x.symbol,weight:weights[i]}))}
const catalogueGate=Boolean(broker.availability_gate);
const out={version:'2.9.0',generated_at:now.toISOString(),run_id:current.run_id||market.run_id||null,broker:{mode:broker.mode||'CURATED_T212_UNIVERSE',authoritative:false,account_specific:false,credentials_required:false,curated_universe:Boolean(broker.curated_universe),availability_gate:catalogueGate,verified:broker.stats?.verified||0,available:broker.stats?.available||0,seed_symbols:broker.stats?.seed_symbols||0},transmission:{version:tx.version||null,method:tx.method||null,stats:tx.stats||{}},openai_jury:{configured:Boolean(OPENAI_KEY),model:OPENAI_MODEL,calls_before:budget.days[day].openai_jury_calls,usd_before:budget.days[day].openai_jury_usd,call_cap:JURY_CALL_CAP,usd_cap:JURY_USD_CAP},strategies:{},summary:{strategies:0,deploy_window:0,scout_window:0,prepare:0,watch:0,do_not_chase:0,early_wave:0,in_sync:0,late_wave:0,broker_verified:0,clean_long_shortage:0,high_transmission:0}};
for(const m of cfg.mechanisms){
  const cur=current.mechanisms?.[m.id]||{state:'UNKNOWN',score:0,market:{score:0,crowding:0},crowd:{phase:'DISCOVERY',priced_in:0,timing_score:0},scout:{eligible:false},alpha:{eligible:false},evidence:[],expected_next:[],invalidation:[]},bench=benchFor(m.id),rows=[],txRows=new Map((tx.mechanisms?.[m.id]?.candidates||[]).map(x=>[x.symbol,x]));
  for(const [symbol,fit,exposure] of seeds.mechanisms?.[m.id]||[]){
    const br=broker.instruments?.[symbol]||{},brokerEligible=br.available===true;if(!brokerEligible)continue;
    const ms=marketScore(symbol,bench),t=txRows.get(symbol)?.transmission||{score:Math.round(fit*.7),risk_adjusted_score:Math.round(fit*.65),label:'UNKNOWN',confidence:30,components:{},passes:{},path:{}},fund=txRows.get(symbol)?.fundamental||null,rank=Math.round(clamp(.55*(t.risk_adjusted_score??t.score??50)+.30*ms.score+.15*fit));
    rows.push({symbol,name:fund?.name||symbol,exposure,fit,rank_score:rank,transmission:t,fundamental:fund,market:ms,broker_verified:Boolean(br.verified),broker_available:true,verification_source:br.verification_source||'USER_CURATED_T212_UNIVERSE'});
  }
  rows.sort((a,b)=>b.rank_score-a.rank_score||b.transmission.score-a.transmission.score||b.fit-a.fit);const top=rows.slice(0,5),clean=top.filter(x=>x.exposure==='DIRECT'&&x.fit>=75&&Number(x.transmission?.score||0)>=58).length,action=actionFor(cur),avgTx=top.length?top.reduce((a,x)=>a+Number(x.transmission?.score||0),0)/top.length:0,avgP1=top.length?top.reduce((a,x)=>a+Number(x.transmission?.passes?.structural?.score||0),0)/top.length:0,avgP2=top.length?top.reduce((a,x)=>a+Number(x.transmission?.passes?.financial?.score||0),0)/top.length:0,timing=Number(cur.crowd?.timing_score??cur.market?.score??0),opportunity=Math.round(clamp(.40*(cur.score||0)+.35*avgTx+.25*timing));
  const strategy={id:m.id,label:m.label,tier:m.tier,state:cur.state||'UNKNOWN',action,opportunity_score:opportunity,causal_score:cur.score||0,market_score:cur.market?.score||0,crowding:cur.market?.crowding||0,crowd:cur.crowd||null,scout:cur.scout||{eligible:false},wave_phase:cur.crowd?.phase||'DISCOVERY',priced_in:cur.crowd?.priced_in??0,crowd_consensus:cur.crowd?.consensus??0,timing_score:timing,transmission_score:+avgTx.toFixed(1),structural_score:+avgP1.toFixed(1),financial_score:+avgP2.toFixed(1),transmission_best:top[0]?.transmission?.score??null,transmission_path:tx.mechanisms?.[m.id]?.model||null,alpha:cur.alpha||{eligible:false},benchmark:bench,top5:top,model_pie:pie(top),clean_direct_count:clean,quality:clean>=4?'CLEAN':clean>=2?'MIXED':'WEAK',broker_strict:catalogueGate,deployable:Boolean(catalogueGate&&action==='DEPLOY_WINDOW'&&clean>=2),summary:cur.summary||'',trigger:(cur.expected_next||[]).slice(0,4),invalidation:(cur.invalidation||[]).slice(0,4),alpha_blockers:cur.alpha?.reasons||[],scout_blockers:cur.scout?.reasons||[],jury:null};
  if(top.length<5)strategy.warning=`Only ${top.length} candidates remain inside the curated Trading 212 universe.`;if(!catalogueGate)strategy.warning='Trading 212 curated universe is unavailable; deployability remains blocked.';if(clean<3)strategy.exposure_warning='Fewer than three high-fit DIRECT companies also clear the Transmission floor; do not manufacture a five-stock basket from weak proxies.';if(cur.crowd?.block_chase)strategy.timing_warning=`${cur.crowd.phase}: estimated ${Math.round(cur.crowd.priced_in||0)}% priced-in. Do not confuse a correct thesis with a good entry.`;out.strategies[m.id]=strategy;
}
const priority=Object.values(out.strategies).filter(x=>['DEPLOY_WINDOW','WAIT_ALPHA_GATE','PREPARE'].includes(x.action)).sort((a,b)=>b.opportunity_score-a.opportunity_score).slice(0,JURY_CALL_CAP);
const jurySchema={type:'object',additionalProperties:false,properties:{verdict:{type:'string',enum:['CLEAN','MIXED','WEAK']},note:{type:'string'},weakest_link:{type:'string'},candidate_notes:{type:'array',items:{type:'object',additionalProperties:false,properties:{symbol:{type:'string'},reason:{type:'string'},risk:{type:'string'}},required:['symbol','reason','risk']}}},required:['verdict','note','weakest_link','candidate_notes']};
async function jury(strategy){if(!OPENAI_KEY||budget.days[day].openai_jury_calls>=JURY_CALL_CAP||budget.days[day].openai_jury_usd>=JURY_USD_CAP)return null;const evidence=(current.mechanisms?.[strategy.id]?.evidence||[]).slice(0,10).map(x=>({phase:x.phase,signal:x.signal,claim:x.claim,source_grade:x.source_grade})),candidates=strategy.top5.map(x=>({symbol:x.symbol,exposure:x.exposure,fit:x.fit,rank_score:x.rank_score,transmission:{score:x.transmission?.score,label:x.transmission?.label,confidence:x.transmission?.confidence,passes:x.transmission?.passes,financials:x.transmission?.financials,caveat:x.transmission?.caveat},market:x.market})),prompt=`Audit an already deterministic two-pass company-transmission map. Do NOT decide whether the mechanism is active and do NOT browse. Pass 1 measures structural exposure; Pass 2 calibrates it with observed fundamentals. Check whether the supplied economic path and both passes support each candidate as a clean equity expression. Do not invent company facts. If financial coverage is weak, explicitly lower confidence.\nMECHANISM=${strategy.id} ${strategy.label}\nSTATE=${strategy.state} causal=${strategy.causal_score} market=${strategy.market_score}\nWAVE=${strategy.wave_phase} priced_in=${strategy.priced_in}\nECONOMIC_PATH=${JSON.stringify(strategy.transmission_path)}\nEVIDENCE=${JSON.stringify(evidence)}\nCANDIDATES=${JSON.stringify(candidates)}`;
  try{const r=await fetch('https://api.openai.com/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${OPENAI_KEY}`,'Content-Type':'application/json'},body:JSON.stringify({model:OPENAI_MODEL,max_completion_tokens:1000,messages:[{role:'system',content:'You are an independent portfolio-mapping auditor. No web search. No investment orders. Be concise, skeptical and evidence-bound.'},{role:'user',content:prompt}],response_format:{type:'json_schema',json_schema:{name:'gearwatch_investment_jury',strict:true,schema:jurySchema}}}),signal:AbortSignal.timeout(45000)}),text=await r.text();if(!r.ok)throw new Error(`OpenAI ${r.status}: ${text.slice(0,180)}`);const j=JSON.parse(text),parsed=JSON.parse(j.choices?.[0]?.message?.content||'{}'),u=j.usage||{},cost=(Number(u.prompt_tokens||0)*.05+Number(u.completion_tokens||0)*.40)/1e6;budget.days[day].openai_jury_calls++;budget.days[day].openai_jury_usd=+(budget.days[day].openai_jury_usd+cost).toFixed(6);return {...parsed,model:j.model||OPENAI_MODEL,usage:u,cost_usd:+cost.toFixed(6)}}catch(e){return {error:String(e.message||e)}}
}
for(const s of priority)s.jury=await jury(s);
out.openai_jury.calls_after=budget.days[day].openai_jury_calls;out.openai_jury.usd_after=budget.days[day].openai_jury_usd;const vals=Object.values(out.strategies);out.summary.strategies=vals.length;out.summary.deploy_window=vals.filter(x=>x.action==='DEPLOY_WINDOW').length;out.summary.scout_window=vals.filter(x=>x.action==='SCOUT_WINDOW').length;out.summary.prepare=vals.filter(x=>x.action==='PREPARE').length;out.summary.watch=vals.filter(x=>x.action==='WATCH').length;out.summary.do_not_chase=vals.filter(x=>x.action==='DO_NOT_CHASE').length;out.summary.early_wave=vals.filter(x=>['PRE_WAVE','EARLY_WAVE'].includes(x.wave_phase)).length;out.summary.in_sync=vals.filter(x=>x.wave_phase==='IN_SYNC').length;out.summary.late_wave=vals.filter(x=>['LATE_WAVE','SATURATED'].includes(x.wave_phase)).length;out.summary.broker_verified=vals.filter(x=>x.broker_strict).length;out.summary.clean_long_shortage=vals.filter(x=>x.clean_direct_count<3).length;out.summary.high_transmission=vals.filter(x=>x.transmission_score>=70).length;
await fs.writeFile('data/investment-layer.json',JSON.stringify(out,null,2)+'\n');await fs.writeFile(budgetPath,JSON.stringify(budget,null,2)+'\n');
console.log(`investment v2.9: strategies=${vals.length} deploy=${out.summary.deploy_window} scout=${out.summary.scout_window} early=${out.summary.early_wave} sync=${out.summary.in_sync} late=${out.summary.late_wave} tx70+=${out.summary.high_transmission} jury=${out.openai_jury.calls_after-out.openai_jury.calls_before} $${Number(out.openai_jury.usd_after-out.openai_jury.usd_before).toFixed(6)}`);
