import {clamp,mean,pct,fetchText} from './pricing-adapters.mjs';

const SPORTS=/\b(parlay|nba|nfl|mlb|nhl|ncaa|wnba|soccer|football|basketball|baseball|hockey|tennis|golf|ufc|fight|match|game|team|player|score|touchdown|goals?|innings?|sets?|quarter|spread|moneyline)\b/i;
const DOMAIN={
 JAPAN_CARRY_UNWIND:[/\b(japan|japanese|yen|boj|jgb)\b/i,/\b(rate|yield|bond|currency|central bank|hike|cut)\b/i],
 GLOBAL_REFINANCING_STRESS:[/\b(recession|default|credit|refinanc|rates?|yield|spread)\b/i],
 ARSENAL_DEPLETION:[/\b(ukraine|iran|war|missile|munition|defen[cs]e|interceptor)\b/i],
 CHEAP_DRONE_SCALING:[/\b(drone|uas|uav|unmanned)\b/i,/\b(war|military|defen[cs]e|ukraine|iran)\b/i],
 UNDERWATER_SECURITY:[/\b(hormuz|shipping|tanker|mine|subsea|underwater|gulf of oman|iran)\b/i],
 OT_CYBER_SHOCK:[/\b(cyber|ransomware|outage|grid|pipeline)\b/i],
 LNG_REROUTING:[/\b(lng|liquefied natural gas|hormuz|gas shipping|tanker)\b/i]
};
export function sanitizeKalshi(obs){if(!obs?.mechanisms)return obs;let rejected=0;for(const [id,m] of Object.entries(obs.mechanisms)){const rules=DOMAIN[id]||[];const clean=(m.hits||[]).filter(x=>{const t=`${x.title||''} ${x.ticker||''}`;if(SPORTS.test(t)){rejected++;return false}if(rules.length&&!rules.every(r=>r.test(t))){rejected++;return false}return true});const liquid=clean.filter(x=>Number.isFinite(x.last_price)&&x.last_price>=0&&x.last_price<=1&&(Number(x.volume)>0||Number(x.open_interest)>0));const sw=liquid.reduce((a,x)=>a+Math.max(1,Math.log10(1+Number(x.volume||0)+Number(x.open_interest||0))),0);const score=sw?liquid.reduce((a,x)=>a+x.last_price*Math.max(1,Math.log10(1+Number(x.volume||0)+Number(x.open_interest||0))),0)/sw*100:null;m.hits=clean;m.pricing_score=score==null?null:Math.round(clamp(score));m.semantic_quality=clean.length?'DOMAIN_MATCH':'NO_RELEVANT_MARKET'}obs.rejected_semantic_hits=rejected;return obs}

function csvLine(line){const out=[];let cur='',q=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'){if(q&&line[i+1]==='"'){cur+='"';i++}else q=!q}else if(c===','&&!q){out.push(cur);cur=''}else cur+=c}out.push(cur);return out}
export async function eiaPublicFallback(){try{const text=await fetchText('https://ir.eia.gov/wpsr/table6.csv');const lines=text.split(/\r?\n/).filter(Boolean),rows=lines.map(csvLine);const candidates=[];for(const r of rows){const joined=r.join(' ').toLowerCase();if(/distillate fuel oil/.test(joined)&&/total/.test(joined)){const nums=r.map(v=>Number(String(v).replace(/,/g,''))).filter(Number.isFinite);if(nums.length)candidates.push({raw:r,value:nums.at(-1)})}}if(!candidates.length)throw new Error('table6.csv distillate total not parsed');const values=candidates.map(x=>x.value).filter(Number.isFinite),latest=values[0],base=mean(values.slice(1,6));const chg=pct(latest,base);return {status:'OK',quality:'PRIMARY_OFFICIAL_PUBLIC',metric:'EIA_WPSR_DISTILLATE_STOCKS',value:latest,unit:'thousand barrels',change_vs_recent_pct:chg==null?null:+chg.toFixed(2),pricing_score:chg==null?null:Math.round(clamp(50-chg*4)),source_url:'https://ir.eia.gov/wpsr/table6.csv',fallback:true}}catch(e){return {status:'ERROR',quality:'PRIMARY_OFFICIAL_PUBLIC',metric:'EIA_WPSR_DISTILLATE_STOCKS',pricing_score:null,error:String(e.message||e),fallback:true}}}

export async function ukmtoPublicFallback(){try{const h=await fetchText('https://www.ukmto.org/'),plain=h.replace(/<[^>]+>/g,' ').replace(/\s+/g,' '),hormuz=(plain.match(/Hormuz/gi)||[]).length,attack=(plain.match(/\bAttack\b|struck|projectile|security incident/gi)||[]).length,mine=(plain.match(/\bmine\b|mining|mine countermeasure/gi)||[]).length,score=(hormuz+attack+mine)?Math.round(clamp(25+Math.min(25,hormuz*2+attack*3+mine*4))):null;return {status:'OK',quality:'PRIMARY_OFFICIAL_PUBLIC',metric:'UKMTO_RECENT_INCIDENTS_HOME',pricing_score:score,mentions:{hormuz,attack,mine},source_url:'https://www.ukmto.org/',fallback:true}}catch(e){return {status:'ERROR',quality:'PRIMARY_OFFICIAL_PUBLIC',metric:'UKMTO_RECENT_INCIDENTS_HOME',pricing_score:null,error:String(e.message||e),fallback:true}}}

export async function mofJgbPublicFallback(){try{const h=await fetchText('https://www.mof.go.jp/english/public_relations/whats_new/2026jgbs.html');const links=[...h.matchAll(/href="([^"]*eresul\/eresul20\d{6}\.htm)"[^>]*>([^<]*)/gi)].slice(0,8);const auctions=[];for(const m of links){try{const u=new URL(m[1],'https://www.mof.go.jp').href,t=(await fetchText(u)).replace(/<[^>]+>/g,' ').replace(/\s+/g,' '),yieldM=t.match(/Yield at the Average Price[^0-9]*([0-9]+\.[0-9]+)%/i)||t.match(/([0-9]+\.[0-9]+)%[^%]{0,80}Weighted Average Price/i),bid=t.match(/Amounts of Competitive Bids[^0-9]*([0-9,]+\.?[0-9]*)/i),accepted=t.match(/Amounts of Bids Accepted[^0-9]*([0-9,]+\.?[0-9]*)/i),yv=yieldM?+yieldM[1]:null,bv=bid?+bid[1].replace(/,/g,''):null,av=accepted?+accepted[1].replace(/,/g,''):null;auctions.push({url:u,title:m[2].replace(/<[^>]+>/g,' ').trim(),average_yield:yv,bid_to_cover:bv&&av?+(bv/av).toFixed(2):null})}catch{}}const ys=auctions.map(x=>x.average_yield).filter(Number.isFinite);if(!auctions.length)throw new Error('no current JGB result links parsed');return {status:'OK',quality:'PRIMARY_OFFICIAL_PUBLIC',metric:'MOF_JGB_AUCTIONS_RECENT',pricing_score:ys.length?Math.round(clamp(30+mean(ys)*14)):null,auctions,source_url:'https://www.mof.go.jp/english/public_relations/whats_new/2026jgbs.html',fallback:true}}catch(e){return {status:'ERROR',quality:'PRIMARY_OFFICIAL_PUBLIC',metric:'MOF_JGB_AUCTIONS_RECENT',pricing_score:null,error:String(e.message||e),fallback:true}}}

export async function improveObservations(observations){if(observations.KALSHI)sanitizeKalshi(observations.KALSHI);if(observations.EIA?.status!=='OK')observations.EIA=await eiaPublicFallback();if(observations.UKMTO?.status!=='OK')observations.UKMTO=await ukmtoPublicFallback();if(observations.MOF_JGB?.status!=='OK'||!Number.isFinite(observations.MOF_JGB?.pricing_score)){const f=await mofJgbPublicFallback();if(f.status==='OK')observations.MOF_JGB=f}return observations}
