import fs from 'node:fs/promises';
import crypto from 'node:crypto';

const mechCfg=JSON.parse(await fs.readFile('config/mechanisms.json','utf8'));
const primary=JSON.parse(await fs.readFile('config/queries.v2.json','utf8'));
const extra=JSON.parse(await fs.readFile('config/queries.v2.extra.json','utf8').catch(()=>'{"mechanisms":{}}'));
const queryCfg={...primary,mechanisms:{...(primary.mechanisms||{}),...(extra.mechanisms||{})}};
const policy=JSON.parse(await fs.readFile('config/policy.v2.json','utf8'));
const previous=JSON.parse(await fs.readFile('data/current.json','utf8').catch(()=>'{"mechanisms":{}}'));
const cachePath='data/query-cache.json';const cache=JSON.parse(await fs.readFile(cachePath,'utf8').catch(()=>'{"version":"2.2.0","entries":{}}'));cache.entries??={};
const now=new Date(),hour=now.getUTCHours(),runId=process.env.GEARWATCH_RUN_ID||`run_${now.toISOString().replace(/[:.]/g,'-')}`,MAX=queryCfg.defaults?.max_results_per_query||8;
const shouldRun=m=>m.tier==='A'||(m.tier==='B'&&hour%12===0)||(m.tier==='C'&&hour===0),selected=mechCfg.mechanisms.filter(shouldRun);
const sleep=ms=>new Promise(r=>setTimeout(r,ms)),hash=s=>crypto.createHash('sha256').update(String(s)).digest('hex').slice(0,20);
const stripHtml=s=>String(s||'').replace(/<!\[CDATA\[|\]\]>/g,'').replace(/<[^>]+>/g,' ').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g,' ').trim();
const xmlTag=(block,tag)=>{const m=block.match(new RegExp(`<${tag}(?:\\s[^>]*)?>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?stripHtml(m[1]):''};const sourceTag=block=>{const m=block.match(/<source(?:\s+url="([^"]+)")?>([\s\S]*?)<\/source>/i);return m?{url:m[1]||'',name:stripHtml(m[2])}:{url:'',name:''}};const domainOf=u=>{try{return new URL(u).hostname.replace(/^www\./,'')}catch{return ''}};
const timeoutMs=policy.retrieval?.source_timeout_ms||6500;let gdeltFailures=0,gdeltCircuit=false;const gdeltThreshold=policy.retrieval?.gdelt_circuit_breaker_failures||2;
async function safeFetch(url,{attempts=1,timeout=timeoutMs}={}){let last;for(let i=0;i<attempts;i++){try{const r=await fetch(url,{headers:{'user-agent':'GearWatch/2.2 causal-research'},signal:AbortSignal.timeout(timeout)});if(!r.ok)throw Object.assign(new Error(`HTTP ${r.status}`),{status:r.status});return r}catch(e){last=e;if(i+1<attempts)await sleep(500)}}throw last}
async function gdelt(query,windowHours){if(gdeltCircuit)throw Object.assign(new Error('GDELT_CIRCUIT_OPEN'),{circuit:true});const end=new Date(),start=new Date(end.getTime()-windowHours*3600e3),fmt=d=>d.toISOString().replace(/[-:TZ.]/g,'').slice(0,14),url=`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(query)}&mode=ArtList&maxrecords=${MAX}&format=json&sort=DateDesc&startdatetime=${fmt(start)}&enddatetime=${fmt(end)}`;try{const r=await safeFetch(url,{attempts:1}),text=await r.text();let j;try{j=JSON.parse(text)}catch{throw new Error(`GDELT_NON_JSON:${text.slice(0,80)}`)}return (j.articles||[]).slice(0,MAX).map(a=>({engine:'gdelt',title:a.title||'',url:a.url||'',domain:a.domain||domainOf(a.url),source_name:a.domain||domainOf(a.url),published_at:a.seendate||'',snippet:'',language:a.language||'',source_country:a.sourcecountry||''}))}catch(e){gdeltFailures++;if(gdeltFailures>=gdeltThreshold)gdeltCircuit=true;throw e}}
async function googleNews(query,windowHours){const days=Math.max(1,Math.ceil(windowHours/24)),q=`${query} when:${days}d`,url=`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-US&gl=US&ceid=US:en`,r=await safeFetch(url,{attempts:1}),xml=await r.text(),items=[...xml.matchAll(/<item>([\s\S]*?)<\/item>/gi)].slice(0,MAX).map(x=>x[1]);return items.map(block=>{const src=sourceTag(block),link=xmlTag(block,'link');return {engine:'google_news',title:xmlTag(block,'title'),url:link,domain:domainOf(src.url)||domainOf(link),source_name:src.name||domainOf(link),published_at:xmlTag(block,'pubDate'),snippet:xmlTag(block,'description'),language:'',source_country:''}})}
function phasesFor(m,q){const prev=previous.mechanisms?.[m.id]||{},phases=['lead'],warmed=(prev.score||0)>=25||['WATCH','ARMING','ACTIVE','SATURATED'].includes(prev.state);if(warmed||(m.tier==='A'&&(hour===0||hour===12)))phases.push('confirm');if(['ACTIVE','SATURATED'].includes(prev.state)||prev.alpha?.eligible)phases.push('lag');return phases.filter(p=>Array.isArray(q?.[p])&&q[p].length)}
function ttlHours(m,phase){if(phase==='lag')return 22;if(phase==='confirm')return m.tier==='A'?10:11;return m.tier==='A'?5:m.tier==='B'?10:22}const cacheKey=(engine,queryId,q)=>hash(`${engine}|${queryId}|${q}`);function cachedRows(key,ttl){const x=cache.entries[key];if(!x)return null;const age=(Date.now()-Date.parse(x.fetched_at||0))/36e5;return Number.isFinite(age)&&age<ttl?x.rows:null}function putCache(key,rows){cache.entries[key]={fetched_at:new Date().toISOString(),rows:rows.slice(0,MAX)}}
const output={version:'2.2.0',run_id:runId,generated_at:now.toISOString(),window_hours:queryCfg.defaults?.window_hours||30,mechanisms:{},errors:[],request_count:0,cache_hits:0,circuits:{gdelt:false}};
for(const m of selected){const qset=queryCfg.mechanisms[m.id];if(!qset){output.errors.push({mechanism_id:m.id,error:'Missing V2 query config'});continue}const bucket={id:m.id,label:m.label,tier:m.tier,queries:[],candidates:[]},dedupe=new Map();for(const phase of phasesFor(m,qset))for(const query of qset[phase]){const queryId=`${m.id}:${phase}:${query.id}`,trace={query_id:queryId,phase:phase.toUpperCase(),signal:query.signal,q:query.q,engines:{},started_at:new Date().toISOString()};for(const engine of queryCfg.defaults?.retrievers||['gdelt','google_news']){const key=cacheKey(engine,queryId,query.q),ttl=ttlHours(m,phase);if(engine==='gdelt'&&gdeltCircuit){trace.engines[engine]={ok:false,skipped:'CIRCUIT_OPEN',ttl_hours:ttl};continue}try{let rows=cachedRows(key,ttl),cached=true;if(!rows){rows=engine==='gdelt'?await gdelt(query.q,output.window_hours):await googleNews(query.q,output.window_hours);putCache(key,rows);output.request_count++;cached=false}else output.cache_hits++;trace.engines[engine]={ok:true,count:rows.length,cached,ttl_hours:ttl};for(const row of rows){const dk=(row.url||row.title).toLowerCase().replace(/[?#].*$/,'');if(!dk)continue;const item={id:hash(`${queryId}|${row.url}|${row.title}`),mechanism_id:m.id,query_id:queryId,phase:phase.toUpperCase(),signal:query.signal,query:query.q,...row,retrieved_at:new Date().toISOString()},existing=dedupe.get(dk);if(!existing)dedupe.set(dk,item);else existing.matched_queries=[...new Set([...(existing.matched_queries||[existing.query_id]),queryId])]}}catch(e){output.request_count++;trace.engines[engine]={ok:false,error:String(e.message||e),ttl_hours:ttl};output.errors.push({mechanism_id:m.id,query_id:queryId,engine,error:String(e.message||e)})}await sleep(80)}trace.finished_at=new Date().toISOString();bucket.queries.push(trace)}bucket.candidates=[...dedupe.values()].sort((a,b)=>String(b.published_at).localeCompare(String(a.published_at))).slice(0,36);output.mechanisms[m.id]=bucket}
output.circuits.gdelt=gdeltCircuit;output.circuits.gdelt_failures=gdeltFailures;for(const [k,v] of Object.entries(cache.entries))if(Date.now()-Date.parse(v.fetched_at||0)>7*864e5)delete cache.entries[k];await fs.mkdir('data/retrieval',{recursive:true});await fs.writeFile('data/retrieval/latest.json',JSON.stringify(output,null,2)+'\n');await fs.writeFile(`data/retrieval/${runId}.json`,JSON.stringify(output,null,2)+'\n');await fs.writeFile(cachePath,JSON.stringify(cache,null,2)+'\n');console.log(`retrieval ${runId}: ${Object.keys(output.mechanisms).length} mechanisms, requests=${output.request_count}, cache=${output.cache_hits}, errors=${output.errors.length}, gdeltCircuit=${gdeltCircuit}`);
