import assert from 'node:assert/strict';
import {clusterEvidence,causalScore,hysteresisState,marketConfirmation,alphaClick} from './score.v2.mjs';
import {parseModelJson,normalizeParsed,mapConcurrent} from './extract-core.mjs';
import {mergeEvidenceMemory,crediblePublishedAt} from './evidence-memory.mjs';
import {deriveFinancialScores,scoreTransmission,structuralTransmission} from './transmission-core.mjs';

const policy={event_clustering:{claim_jaccard_threshold:.5,max_time_gap_hours:72,min_token_length:4},evidence_memory:{ttl_hours:{LEAD:168,CONFIRM:72,LAG:336},half_life_hours:{LEAD:72,CONFIRM:36,LAG:168},min_weight:.25,max_items_per_mechanism:96},state_gates:{active_confirmation_runs:2,deactivate_confirmation_runs:2,fast_path_causal:86},alpha:{min_causal:60,min_market:20,max_market:64,max_crowding:66,min_independent_domains:2,require_confirm:true,require_stable_active:true,max_lag_share:.45,reliability_gate_after_samples:5,min_empirical_reliability:.35}};
const base={valid:true,contradiction:false,phase:'LEAD',signal:'REFINERY_OUTAGE',source_grade:.92,published_at:new Date().toISOString()};
const mirrored=[{...base,claim:'Major refinery extends hydrocracker outage after equipment failure',source_url:'https://reuters.com/a',source_domain:'reuters.com'},{...base,claim:'Major refinery extends its hydrocracker outage following equipment failure',source_url:'https://example.com/mirror',source_domain:'example.com'},{...base,claim:'Major refinery hydrocracker outage extended after equipment failure',source_url:'https://news.example/x',source_domain:'news.example'}];
const clusters=clusterEvidence(mirrored,policy.event_clustering);assert.equal(clusters.length,1,'syndicated mirrors must cluster into one event');assert.equal(clusters[0].member_count,3);const distinct=[...mirrored,{...base,claim:'Second refinery unexpectedly shuts diesel unit after fire',source_url:'https://apnews.com/b',source_domain:'apnews.com'}];assert.equal(clusterEvidence(distinct,policy.event_clustering).length,2,'materially different events must remain separate');const scored=causalScore(mirrored,[],policy.event_clustering);assert.equal(scored.event_count,1);assert.equal(scored.duplicate_count,2);

const causal={score:72,total:3,counts:{LEAD:1,CONFIRM:1,LAG:0},domains:['a.com','b.com'],lag_share:0};const first=hysteresisState({raw:'ACTIVE',previous:'ARMING',pending:null,causal,policy});assert.equal(first.state,'ARMING');assert.equal(first.pending.streak,1);const second=hysteresisState({raw:'ACTIVE',previous:'ARMING',pending:first.pending,causal,policy});assert.equal(second.state,'ACTIVE','ACTIVE must require the configured persistence');const down1=hysteresisState({raw:'WATCH',previous:'ACTIVE',pending:null,causal:{...causal,score:30},policy});assert.equal(down1.state,'ACTIVE');assert.equal(down1.pending.streak,1);const down2=hysteresisState({raw:'WATCH',previous:'ACTIVE',pending:down1.pending,causal:{...causal,score:30},policy});assert.equal(down2.state,'WATCH','ACTIVE demotion must also require persistence');const fast=hysteresisState({raw:'ACTIVE',previous:'ARMING',pending:null,causal:{...causal,score:90},policy});assert.equal(fast.state,'ACTIVE','overwhelming causal evidence may use fast path');

const benchmark={ticker:'XLE',ret1:1,ret5:2,ret20:4,volumeZ:0,intraday:{ret30m:.2,ret2h:.4}},winner={ticker:'ASC',ret1:2,ret5:5,ret20:8,volumeZ:1.2,above20:true,above50:true,intraday:{ret30m:.6,ret2h:1.4}},laggard={ticker:'BAD',ret1:.5,ret5:1,ret20:2,volumeZ:.1,above20:true,above50:true,intraday:{ret30m:0,ret2h:.1}};const strong=marketConfirmation({positive:[winner],negative:[],benchmark}),weak=marketConfirmation({positive:[laggard],negative:[],benchmark});assert.ok(strong.score>weak.score);assert.ok(strong.avg.rel5>0&&strong.avg.rel2h>0);assert.ok(weak.avg.rel5<0);const shortWinner={ticker:'AIRLINE',ret1:-2,ret5:-4,ret20:-5,volumeZ:1,above20:false,above50:false,intraday:{ret30m:-.4,ret2h:-1}};const inverse=marketConfirmation({positive:[],negative:[shortWinner],benchmark:{...benchmark,ret1:0,ret5:0,ret20:0,intraday:{ret30m:0,ret2h:0}}});assert.ok(inverse.avg.rel5>0);

const alphaBlocked=alphaClick({causal,market:{score:35,crowding:20},policy,reliability:{samples:0,hit_rate:null},state:'ARMING'});assert.equal(alphaBlocked.eligible,false);assert.ok(alphaBlocked.reasons.includes('STATE_NOT_STABLY_ACTIVE'));const alphaActive=alphaClick({causal,market:{score:35,crowding:20},policy,reliability:{samples:0,hit_rate:null},state:'ACTIVE'});assert.equal(alphaActive.eligible,true);

const malformed='```json\n{"summary":"ok","items":[{"candidateId":"c1","fact":"refinery outage","relevance":0.9,}],"expectedNext":[],"invalidation":[],}\n```';const repaired=parseModelJson(malformed);assert.ok(repaired.value);const normalized=normalizeParsed(repaired.value);assert.equal(normalized.items[0].candidate_id,'c1');assert.equal(normalized.items[0].claim,'refinery outage');const partial=normalizeParsed({overview:'x',evidence:[{sourceId:'a',statement:'b'}]});assert.equal(partial.summary,'x');assert.equal(partial.expected_next.length,0);let active=0,maxActive=0;const outputs=await mapConcurrent([1,2,3,4,5],3,async x=>{active++;maxActive=Math.max(maxActive,active);await new Promise(r=>setTimeout(r,10));active--;return x*2});assert.deepEqual(outputs,[2,4,6,8,10]);assert.ok(maxActive<=3&&maxActive>=2);

const t0='2026-09-04T00:00:00.000Z',t1='2026-09-04T06:00:00.000Z',tOld='2026-08-20T00:00:00.000Z',ev={valid:true,phase:'LEAD',signal:'REFINERY_AVAILABILITY',claim:'Refinery extends turnaround',source_url:'https://example.com/refinery',source_domain:'example.com',source_grade:.8,published_at:'2026-09-03T12:00:00Z',retrieved_at:t0};const seeded=mergeEvidenceMemory([ev],[],policy,t0);assert.equal(seeded.length,1);assert.equal(seeded[0].memory_status,'OBSERVED');assert.equal(seeded[0].memory_weight,1);const carried=mergeEvidenceMemory([],seeded,policy,t1);assert.equal(carried.length,1,'unrediscovered evidence should remain in living memory');assert.equal(carried[0].memory_status,'CARRIED');assert.ok(carried[0].memory_weight<1&&carried[0].memory_weight>.9,'six-hour carry should decay slightly, not disappear');const expired=mergeEvidenceMemory([],seeded,policy,'2026-09-12T00:00:01Z');assert.equal(expired.length,0,'evidence must expire after deterministic phase TTL');const fakeDate={engine:'openrouter_web_fallback',published_at:t0,retrieved_at:t0};assert.equal(crediblePublishedAt(fakeDate),null,'retrieval time must never masquerade as publication time');assert.equal(crediblePublishedAt({...fakeDate,engine:'google_news',published_at:tOld}),tOld);

const fundamental={quality:'LIVE_YAHOO',financials:{revenue:1_000_000_000,revenue_prev:900_000_000,operating_income:150_000_000,operating_income_prev:100_000_000,cfo:180_000_000,capex:60_000_000,assets:1_500_000_000,liabilities:600_000_000,cash:200_000_000,debt:250_000_000,shares:50_000_000}};const fin=deriveFinancialScores(fundamental,20,'CYCLICAL_MARGIN');assert.ok(fin.observed_weight>=.9);assert.ok(fin.cash_conversion>50);assert.ok(fin.balance>40);assert.equal(fin.metrics.market_cap,1_000_000_000);
const txModel={mode:'CYCLICAL_MARGIN',shock:'scarcity',earnings_channel:'margin expansion',bridge:['scarcity','margin','FCF'],diluters:['hedges'],defaults:{bottleneck:90,margin_capture:92,duration:70,capex_optionality:60}};const p1=structuralTransmission({fit:95,exposure:'DIRECT',model:txModel}),txDirect=scoreTransmission({fit:95,exposure:'DIRECT',model:txModel,fundamental,price:20}),txNoFin=scoreTransmission({fit:95,exposure:'DIRECT',model:txModel,fundamental:{quality:'STRUCTURAL_ONLY',coverage:0},price:null}),txProxy=scoreTransmission({fit:60,exposure:'SECOND_ORDER',model:txModel,fundamental:{quality:'STRUCTURAL_ONLY',coverage:0},price:null});assert.equal(txNoFin.score,p1.score,'without observed fundamentals Pass 2 must not move Pass 1');assert.ok(txDirect.passes.financial.coverage>.8);assert.equal(txDirect.passes.final.delta,txDirect.score-txDirect.passes.structural.score);assert.ok(txDirect.score>txProxy.score,'direct high-fit transmission must outrank weak proxy');assert.ok(txDirect.confidence>txProxy.confidence);assert.ok(txDirect.components.exposure>txProxy.components.exposure);assert.equal(txDirect.path.earnings_channel,'margin expansion');

console.log('GearWatch V2.8 selftest OK: causal gates + living memory + Company Transmission 2-pass');
