import fs from 'node:fs/promises';
const html=await fs.readFile('index.html','utf8'),portfolio=await fs.readFile('portfolio.html','utf8'),fail=[];const gate=(n,ok,w)=>{if(!ok)fail.push(`${n}: ${w}`);console.log(`${ok?'PASS':'FAIL'} · ${n}`)},pos=s=>html.indexOf(s);
gate('Decision hierarchy',pos('4 · Causal')>=0&&pos('5 · Pass 1')>pos('4 · Causal')&&pos('6 · Pass 2')>pos('5 · Pass 1')&&pos('7 · Final TX')>pos('6 · Pass 2')&&pos('8 · Market Vote')>pos('7 · Final TX')&&pos('9 · Crowd Phase')>pos('8 · Market Vote')&&pos('10 · Pool → Top 5')>pos('9 · Crowd Phase'),'Expected causal → transmission → market → pool ordering');
gate('Candidate pool visible',html.includes('Candidate pool → Top 5 executable')&&html.includes('top_candidates'),'Broad research pool must be visible while execution remains Top5');
gate('Top5 execution marker',html.includes('<span class=exec>EXEC</span>'),'Executable shortlist must be distinct from research pool');
gate('Broker simplicity',!html.includes('trading212.com')&&html.includes('T212 ✓'),'No broker links or credential UX');
gate('Three-metric card hierarchy',html.includes('<span>CAUSAL</span>')&&html.includes('<span>FINAL TX</span>')&&html.includes('<span>MARKET</span>'),'Cards keep primary metrics');
gate('Two-pass explainability',html.includes('PASS 1 · STRUCTURAL')&&html.includes('PASS 2 · FINANCIAL')&&html.includes('FINAL TX'),'Expose both passes and final');
gate('Progressive disclosure',html.includes('<details class="company">')&&html.includes('<summary>'),'Company diagnostics collapse');
gate('Scout is not Deploy',html.includes('SCOUT_WINDOW')&&html.includes('No equivale a Deploy'),'Scout distinction required');
gate('Priced-in warning',html.includes('DO NOT CHASE')&&html.includes('priced-in'),'Late timing visible');
gate('Capital not social chatter',html.includes('Crowd = comportamiento agregado del capital'),'Crowd is capital behavior');
gate('Shadow visible main dashboard',html.includes('Shadow $500')&&html.includes('LIVE EXECUTION = OFF')&&html.includes('NO SETUP = NO TRADE'),'Shadow sleeve must be first-class on main dashboard');
gate('SGMOQ visible lock',html.includes('SGMOQ 🔒 LOCKED OUT'),'Protected position visible');
gate('Benchmark visible',html.includes('Alpha vs QQQ')&&html.includes('vs SPX'),'Benchmark comparison required');
gate('Audit visible',html.includes('System audit')&&html.includes('AUDIT.verdict'),'Operational audit visible');
gate('Modal semantics',html.includes('role="dialog"')&&html.includes('aria-modal="true"')&&html.includes('aria-label="Cerrar dossier"'),'Accessible modal');
gate('Keyboard activation',html.includes("e.key==='Enter'||e.key===' '")&&html.includes("if(e.key==='Escape')closeModal()"),'Keyboard controls');
gate('Visible focus',html.includes(':focus-visible'),'Visible focus');gate('Reduced motion',html.includes('@media(prefers-reduced-motion:reduce)'),'Reduced motion');gate('Mobile collapse',html.includes('@media(max-width:900px)')&&html.includes('.passstrip{grid-template-columns:1fr}'),'Mobile layout');
gate('Portfolio mode obvious',portfolio.includes('SHADOW <span>SLEEVE</span>')&&portfolio.includes('LIVE EXECUTION = OFF'),'Dedicated portfolio remains shadow');gate('Budget visible',portfolio.includes('$500 BUDGET')&&portfolio.includes('$80 MAX')&&portfolio.includes('6 SLOTS'),'Constraints visible');gate('Protected position visible',portfolio.includes('SGMOQ 🔒')&&portfolio.includes('SGMOQ · LOCKED OUT'),'SGMOQ dedicated page lock');gate('No-trade is first class',portfolio.includes('Nada. Eso también es una decisión.')&&portfolio.includes('NO SETUP = NO TRADE'),'No trade first class');gate('Paper ledger visible',portfolio.includes('paper-portfolio.json')&&portfolio.includes('trade-journal.json'),'Explicit ledgers');
if(fail.length){console.error(`\nUI/UX audit failed (${fail.length}):\n- ${fail.join('\n- ')}`);process.exit(1)}console.log('\nGearWatch UI/UX audit OK · 24/24 gates');
