import fs from 'node:fs/promises';
const html=await fs.readFile('index.html','utf8'),js=await fs.readFile('lib/butterfly-dashboard.mjs','utf8'),bootstrap=await fs.readFile('lib/bootstrap.mjs','utf8').catch(()=>''),audit=await fs.readFile('lib/economist-shock-audit.mjs','utf8').catch(()=>''),liveEvidence=await fs.readFile('lib/economist-live-evidence.mjs','utf8').catch(()=>''),portfolio=await fs.readFile('portfolio.html','utf8'),pkg=JSON.parse(await fs.readFile('package.json','utf8')),pricing=JSON.parse(await fs.readFile('config/pricing-sensors.json','utf8').catch(()=>'{"mechanisms":{}}')),research=JSON.parse(await fs.readFile('data/window-research.json','utf8').catch(()=>'{"facts":[]}')),src=html+'\n'+js+'\n'+bootstrap+'\n'+audit+'\n'+liveEvidence,fail=[];
const gate=(n,ok,w)=>{if(!ok)fail.push(`${n}: ${w}`);console.log(`${ok?'PASS':'FAIL'} · ${n}`)};
gate('Butterfly garden identity',html.includes('JARDÍN DE LAS')&&html.includes('MARIPOSAS')&&html.includes('Causal Butterfly Radar'),'Primary product identity');
gate('Ten mechanisms by default',js.includes('let SHOW=10'),'Default must be ten');
gate('10/20/26 disclosure',html.includes('data-n="10"')&&html.includes('data-n="20"')&&html.includes('data-n="26"'),'Count selector');
gate('Mechanism maturity bar',src.includes('ENGRANAJE MONTADO')&&src.includes('class="fill'),'Causal maturity bar');
gate('Market discount bar',src.includes('MERCADO DESCONTADO')&&src.includes("'market'"),'Priced-in bar');
gate('Human-first card',src.includes('Por qué importa')&&src.includes('Qué falta')&&src.includes('Piezas expuestas'),'Human explanation');
gate('Root causes visible',html.includes('Causas raíz')&&js.includes('renderRoots')&&js.includes("root:'Hormuz"),'Root-driver grouping');
gate('Daily judge component visible',html.includes('id="briefing"')&&js.includes('renderBriefing')&&js.includes('Briefing diario del juez'),'UI contract must not depend on transient daily data contents');
gate('Butterfly ranking',js.includes('butterflyScore')&&js.includes('prioridad ${bf}/100'),'Rank by causal/pricing gap');
gate('No return target on home',!src.includes('expected_return_pct')&&!src.includes('target_return_pct')&&!html.includes('OBJETIVO DE RETORNO'),'No low-return screener framing');
gate('Progressive engine disclosure',html.includes('<details class="card engine">')&&html.includes('10 pasos'),'Engine details hidden');
gate('Human dossier',js.includes('Dossier humano')&&js.includes('Lectura del juez')&&js.includes('Cadena causal')&&js.includes('Qué está viendo el motor'),'Detailed explanation');
gate('Five company pieces max',js.includes('topPieces(s,5)')&&js.includes('Piezas empresariales'),'Company detail');
gate('Already-moved warning',js.includes('ya han corrido')&&js.includes('ret20'),'Do not chase warning');
gate('Sensor blindspots',html.includes('¿Dónde puede estar ciego?')&&js.includes('BRIEF.blindspots'),'Blindspot panel');
gate('Counter-UAS sensor coverage',js.includes('COUNTER_UAS_COST_CURVE')&&Array.isArray(pricing.mechanisms?.COUNTER_UAS_COST_CURVE)&&pricing.mechanisms.COUNTER_UAS_COST_CURVE.length>0,'Critical sensor must remain structurally covered even when not a current blindspot');
gate('Modal semantics',html.includes('role="dialog"')&&html.includes('aria-modal="true"'),'Modal');
gate('Keyboard activation',js.includes("e.key==='Enter'||e.key===' '")&&js.includes("if(e.key==='Escape')closeModal()"),'Keyboard');
gate('Visible focus',html.includes(':focus-visible'),'Focus');
gate('Mobile collapse',html.includes('@media(max-width:720px)')&&html.includes('.mechs,.briefgrid,.roots,.side,.steps{grid-template-columns:1fr}'),'Mobile');
gate('Dashboard module separated',(html.includes("import('./lib/butterfly-dashboard.mjs')")||(html.includes("import('./lib/bootstrap.mjs')")&&bootstrap.includes("load('lib/butterfly-dashboard.mjs')"))),'V4 module reachable directly or through bootstrap');
gate('AstroShock audit loaded',bootstrap.includes("load('lib/economist-shock-audit.mjs')")&&audit.includes('AUDIT DE EVIDENCIA'),'Deep-research audit layer must load after economist phase');
gate('Astrology has zero causal weight',audit.includes('0% causal weight')&&research.methodology?.principle?.includes('timing hypotheses'),'Astrology must stay timing-only');
gate('Correlation sample guard',audit.includes('min_astro_overlap_n')&&audit.includes('min_correlation_n')&&Number(research.methodology?.min_astro_overlap_n)>=8,'Do not publish tiny-n correlations');
gate('Reference provenance visible',audit.includes('GIT_BACKFILL = reconstruido')&&audit.includes('LIVE = capturado'),'Backfill and live must never be conflated');
gate('Research ledger sourced',Array.isArray(research.facts)&&research.facts.length>=6&&research.facts.some(x=>x.source_type==='OFFICIAL')&&research.facts.every(x=>x.source?.url),'Evidence ledger requires sourced facts');
gate('Falsifiers explicit',Array.isArray(research.falsifiers)&&research.falsifiers.length>=3&&audit.includes('Falsadores'),'Window thesis must be falsifiable');
gate('Live research UI loaded',bootstrap.includes("load('lib/economist-live-evidence.mjs')")&&liveEvidence.includes('published_at explícito'),'Publication-dated live evidence must render inside economist audit');
gate('Live research refresh wired',pkg.scripts?.['window:research']?.includes('window-research-refresh.mjs')&&pkg.scripts?.['scan:v3']?.includes('window:research'),'Every causal scan must refresh the live research ledger');
gate('Portfolio mode obvious',portfolio.includes('SHADOW <span>SLEEVE</span>')&&portfolio.includes('LIVE EXECUTION = OFF'),'Dedicated shadow');
gate('Budget visible',portfolio.includes('$500 BUDGET')&&portfolio.includes('$80 MAX')&&portfolio.includes('6 SLOTS'),'Constraints');
gate('Protected position visible',portfolio.includes('SGMOQ 🔒')&&portfolio.includes('SGMOQ · LOCKED OUT'),'Dedicated lock');
gate('No-trade is first class',portfolio.includes('Nada. Eso también es una decisión.')&&portfolio.includes('NO SETUP = NO TRADE'),'No trade');
if(fail.length){console.error(`\nUI/UX audit failed (${fail.length}):\n- ${fail.join('\n- ')}`);process.exit(1)}console.log('\nGearWatch V4.6 UI/UX audit OK · 32/32 gates');
