import fs from 'node:fs/promises';
const html=await fs.readFile('index.html','utf8');
const js=await fs.readFile('lib/product-dashboard.mjs','utf8');
const bootstrap=await fs.readFile('lib/bootstrap.mjs','utf8').catch(()=>'');
const audit=await fs.readFile('lib/economist-shock-audit.mjs','utf8').catch(()=>'');
const liveEvidence=await fs.readFile('lib/economist-live-evidence.mjs','utf8').catch(()=>'');
const portfolio=await fs.readFile('portfolio.html','utf8');
const pkg=JSON.parse(await fs.readFile('package.json','utf8'));
const pricing=JSON.parse(await fs.readFile('config/pricing-sensors.json','utf8').catch(()=>'{"mechanisms":{}}'));
const research=JSON.parse(await fs.readFile('data/window-research.json','utf8').catch(()=>'{"facts":[]}'));
const history=JSON.parse(await fs.readFile('data/history/window-snapshots.json','utf8').catch(()=>'{"snapshots":[]}'));
const src=html+'\n'+js+'\n'+bootstrap+'\n'+audit+'\n'+liveEvidence,fail=[];
const gate=(n,ok,w)=>{if(!ok)fail.push(n+': '+w);console.log((ok?'PASS':'FAIL')+' · '+n)};
gate('Human product identity',html.includes('HECHOS → CAUSAS → CONSECUENCIAS → EMPRESAS → DECISIÓN')&&html.includes('ENTIENDE QUÉ MUEVE EL'),'Landing must explain the product before jargon');
gate('World-at-a-glance layer',html.includes('id="world"')&&js.includes('renderWorld'),'Top-level macro translation');
gate('Three human stories',html.includes('id="stories"')&&js.includes('renderStories')&&js.includes('VER POR QUÉ'),'Top causal stories must be explainable');
gate('Scenario translation',html.includes('id="capital"')&&html.includes('SIMULACIÓN · NO ORDEN AUTOMÁTICA')&&js.includes('renderScenario'),'Money translation without auto-trading');
gate('No return target framing',!src.includes('expected_return_pct')&&!src.includes('target_return_pct')&&!html.includes('OBJETIVO DE RETORNO'),'Do not turn product into a return screener');
gate('Master narrative history',html.includes('Gráfico maestro · todas las narrativas pujando')&&js.includes('renderMaster')&&js.includes('pressure')&&js.includes('priced_in'),'Narratives must be visible through time');
gate('Real historical source',js.includes("data/history/window-snapshots.json")&&Array.isArray(history.snapshots)&&history.snapshots.length>1,'Master chart must use persisted snapshots');
gate('History-of-the-story dossier',js.includes('Historia de la historia')&&js.includes('historyStats')&&js.includes('historyCard'),'Each mechanism needs birth/peak/now');
gate('Narrative transition memory',js.includes('narrativeEvents')&&html.includes('id="history-events"'),'Important state changes must surface');
gate('CoinMarketCap mechanism grid',html.includes('CoinMarketCap de mecanismos')&&html.includes('id="mech-body"')&&js.includes('renderGrid'),'All mechanisms must be browsable');
gate('Grid search and stage filter',html.includes('id="mech-search"')&&html.includes('id="mech-stage"'),'Retail-readable discovery');
gate('Human stages',js.includes('DESCUBRIMIENTO')&&js.includes('TEMPRANO')&&js.includes('DESARROLLÁNDOSE')&&js.includes('DESCONTADO')&&js.includes('HA CORRIDO')&&js.includes('CONTRADICCIÓN'),'Technical states need human translation');
gate('Causal vs priced separation',js.includes('CAUSALIDAD')&&js.includes('MERCADO DESCONTADO')&&js.includes('gap(m)'),'Do not conflate evidence with price action');
gate('Attention separate from causality',js.includes('attention(m)')&&js.includes('Atención pública ≠ causalidad')&&html.includes('Google Trends no entra en el score causal'),'Buzz must never add causal weight');
gate('Google Trends drill-through',js.includes('trends.google.com/trends/explore')&&js.includes('ABRIR GOOGLE TRENDS'),'Trend interest should be inspectable');
gate('Evidence drill-down',js.includes('Hechos que sostienen o contradicen')&&js.includes('source_url'),'Claims must lead back to evidence');
gate('Falsification layer',js.includes('Qué lo invalidaría')&&js.includes('invalidation'),'A thesis must be able to die');
gate('Company translation',js.includes('Piezas empresariales')&&js.includes('COMPANY_ROLES'),'Mechanism must connect to business economics');
gate('Already-moved protection',js.includes('HA CORRIDO')&&js.includes('no perseguir')||js.includes('no perseguir una reacción'),'Do not chase mature stories');
gate('Modal semantics',html.includes('role="dialog"')&&html.includes('aria-modal="true"'),'Accessible dossier container');
gate('Responsive product shell',html.includes('@media(max-width:700px)')&&html.includes('.stories,.two,.world,.allocs,.history-events'),'Mobile layout');
gate('AstroShock demoted to timing',html.includes('Un reloj, no una causa')&&html.includes('0% PESO CAUSAL'),'Astrology is timing-only');
gate('Advanced Astro lab progressive disclosure',html.includes('ABRIR ASTROSHOCK / ECONOMIST LAB')&&html.includes('id="event-window"')&&bootstrap.includes("load('lib/economist-shock-phase.mjs')"),'Deep layer stays available without hijacking landing');
gate('Deep evidence audit still loaded',bootstrap.includes("load('lib/economist-shock-audit.mjs')")&&audit.includes('AUDIT DE EVIDENCIA'),'Research audit must survive redesign');
gate('Astrology causal-weight guard',audit.includes('0% causal weight')&&research.methodology?.principle?.includes('timing hypotheses'),'Astrology cannot affect causal score');
gate('Correlation sample guard',audit.includes('min_astro_overlap_n')&&Number(research.methodology?.min_astro_overlap_n)>=8,'No tiny-n correlations');
gate('Reference provenance visible',audit.includes('GIT_BACKFILL = reconstruido')&&audit.includes('LIVE = capturado'),'Historical provenance remains explicit');
gate('Live evidence layer',bootstrap.includes("load('lib/economist-live-evidence.mjs')")&&liveEvidence.includes('published_at explícito'),'Freshness requires explicit publication dates');
gate('Critical sensor coverage',Array.isArray(pricing.mechanisms?.COUNTER_UAS_COST_CURVE)&&pricing.mechanisms.COUNTER_UAS_COST_CURVE.length>0,'Structural coverage remains intact');
gate('Window research refresh wired',pkg.scripts?.['scan:v3']?.includes('window:research'),'Every full scan refreshes window research');
gate('Portfolio remains shadow-only',portfolio.includes('LIVE EXECUTION = OFF')&&portfolio.includes('NO SETUP = NO TRADE'),'Product redesign must not enable live trading');
gate('New dashboard is bootstrap entry',bootstrap.includes("load('lib/product-dashboard.mjs')"),'Human-first layer must load first');
if(fail.length){console.error('\nGearWatch V5 UI/UX audit failed ('+fail.length+'):\n- '+fail.join('\n- '));process.exit(1)}
console.log('\nGearWatch V5 UI/UX audit OK · 32/32 gates');
